SUMO - Simulation of Urban MObility: NBOwnTLDef Class Reference
NBOwnTLDef Class Reference
A traffic light logics which must be computed (only nodes/edges are given)
#include <NBOwnTLDef.h>
Data Structures
class edge_by_incoming_priority_sorter
Sorts edges by their priority within the node they end at.
Public Types
enum TLColor {
TLCOLOR_RED, TLCOLOR_YELLOW, TLCOLOR_REDYELLOW, TLCOLOR_GREEN,
TLCOLOR_BLINK
}
An enumeration of possible tl-signal states.
Public Member Functions
void addControlledInnerEdges (const std::vector< std::string > &edges)
Adds the given ids into the list of inner edges controlled by the tls.
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void clearParameter ()
Clears the parameter map.
NBTrafficLightLogic * compute (const NBEdgeCont &ec, OptionsCont &oc)
Computes the traffic light logic.
bool foes (const NBEdge *const from1, const NBEdge *const to1, const NBEdge *const from2, const NBEdge *const to2) const
Returns the information whether the given flows cross.
bool forbids (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
std::vector< std::string > getControlledInnerEdges () const
Retrieve the ids of edges explicitly controlled by the tls.
const NBConnectionVector & getControlledLinks () const
returns the controlled links (depends on previous call to collectLinks)
const std::string & getID () const
Returns the id.
const EdgeVector & getIncomingEdges () const
Returns the list of incoming edges (must be build first)
const std::map< std::string,
std::string > & getMap () const
Returns the inner key/value map.
SUMOTime getOffset ()
Returns the offset.
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
const std::string & getProgramID () const
Returns the ProgramID.
TrafficLightType getType () const
get the algorithm type (static etc..)
bool isLeftMover (const NBEdge *const from, const NBEdge *const to) const
returns the information whether the given link is a left-mover
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
bool mustBrake (const NBEdge *const from, const NBEdge *const to) const
Returns the information whether the described flow must let any other flow pass.
bool mustBrake (const NBConnection &possProhibited, const NBConnection &possProhibitor, bool regardNonSignalisedLowerPriority) const
Returns the information whether the described flow must let the other flow pass.
bool mustBrake (const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether the described flow must let any other flow pass.
NBOwnTLDef (const std::string &id, const std::vector< NBNode * > &junctions, SUMOTime offset, TrafficLightType type)
Constructor.
NBOwnTLDef (const std::string &id, NBNode *junction, SUMOTime offset, TrafficLightType type)
Constructor.
NBOwnTLDef (const std::string &id, SUMOTime offset, TrafficLightType type)
Constructor.
void setID (const std::string &newID)
resets the id
void setParticipantsInformation ()
Builds the list of participating nodes/edges/links.
void setProgramID (const std::string &programID)
Sets the programID.
void setSinglePhase ()
Forces the definition not to compute an additional phase for left-movers.
virtual void shiftTLConnectionLaneIndex (NBEdge *edge, int offset)
patches (loaded) signal plans by modifying lane indices
~NBOwnTLDef ()
Destructor.
Public methods from NBTrafficLightDefinition-interface
void remapRemoved (NBEdge *removed, const EdgeVector &incoming, const EdgeVector &outgoing)
Replaces occurences of the removed edge in incoming/outgoing edges of all definitions.
void setTLControllingInformation (const NBEdgeCont &ec) const
Informs edges about being controlled by a tls.
Access to controlled nodes
virtual void addNode (NBNode *node)
Adds a node to the traffic light logic.
virtual void removeNode (NBNode *node)
Removes the given node from the list of controlled nodes.
const std::vector< NBNode * > & getNodes () const
Returns the list of controlled nodes.
Static Public Member Functions
static std::string addPedestrianPhases (NBTrafficLightLogic *logic, SUMOTime greenTime, std::string state, const std::vector< NBNode::Crossing > &crossings, const EdgeVector &fromEdges, const EdgeVector &toEdges)
add 1 or 2 phases depending on the presence of pedestrian crossings
static std::string patchStateForCrossings (const std::string &state, const std::vector< NBNode::Crossing > &crossings, const EdgeVector &fromEdges, const EdgeVector &toEdges)
compute phase state in regard to pedestrian crossings
Static Public Attributes
static const std::string DefaultProgramID = "0"
Protected Member Functions
virtual bool amInvalid () const
void collectAllLinks ()
helper method for use in NBOwnTLDef and NBLoadedSUMOTLDef
void collectEdges ()
Build the list of participating edges.
unsigned int computeBrakingTime (SUMOReal minDecel) const
Computes the time vehicles may need to brake.
SUMOReal computeUnblockedWeightedStreamNumber (const NBEdge *const e1, const NBEdge *const e2)
Returns how many streams outgoing from the edges can pass the junction without being blocked.
std::pair< NBEdge *, NBEdge * > getBestCombination (const EdgeVector &edges)
Returns the combination of two edges from the given which has most unblocked streams.
std::pair< NBEdge *, NBEdge * > getBestPair (EdgeVector &incoming)
Returns the combination of two edges from the given which has most unblocked streams.
SUMOReal getDirectionalWeight (LinkDirection dir)
Returns the weight of a stream given its direction.
int getToPrio (const NBEdge *const e)
Returns this edge's priority at the node it ends at.
Protected methods from NBTrafficLightDefinition-interface
NBTrafficLightLogic * myCompute (const NBEdgeCont &ec, unsigned int brakingTimeSeconds)
Computes the traffic light logic finally in dependence to the type.
void collectNodes ()
Collects the nodes participating in this traffic light.
void collectLinks ()
Collects the links participating in this traffic light
Exceptions
ProcessError If a link could not be found.
void replaceRemoved (NBEdge *removed, int removedLane, NBEdge *by, int byLane)
Replaces a removed edge/lane.
Protected Attributes
std::set< std::string > myControlledInnerEdges
Set of inner edges that shall be controlled, though.
NBConnectionVector myControlledLinks
The list of controlled links.
std::vector< NBNode * > myControlledNodes
The container with participating nodes.
EdgeVector myEdgesWithin
The list of edges within the area controlled by the tls.
std::string myID
The name of the object.
EdgeVector myIncomingEdges
The list of incoming edges.
SUMOTime myOffset
The offset in the program.
std::string mySubID
The tls program's subid.
TrafficLightType myType
The algorithm type for the traffic light.
Private Attributes
bool myHaveSinglePhase
Whether left-mover should not have an additional phase.
Detailed Description
A traffic light logics which must be computed (only nodes/edges are given)
Definition at line 54 of file NBOwnTLDef.h.
Member Enumeration Documentation
enum NBTrafficLightDefinition::TLColor inherited
An enumeration of possible tl-signal states.
Enumerator
TLCOLOR_RED
Signal shows red.
TLCOLOR_YELLOW
Signal shows yellow.
TLCOLOR_REDYELLOW
Signal shows red/yellow (unused)
TLCOLOR_GREEN
Signal shows green.
TLCOLOR_BLINK
Signal is blinking yellow.
Definition at line 84 of file NBTrafficLightDefinition.h.
Constructor & Destructor Documentation
NBOwnTLDef::NBOwnTLDef (const std::string & id, const std::vector< NBNode * > & junctions, SUMOTime offset, TrafficLightType type)
Constructor.
Parameters
[in] id The id of the tls
[in] junctions Junctions controlled by this tls
[in] offset The offset of the plan
[in] type The algorithm type for the computed traffic light
Definition at line 55 of file NBOwnTLDef.cpp.
NBOwnTLDef::NBOwnTLDef (const std::string & id, NBNode * junction, SUMOTime offset, TrafficLightType type)
Constructor.
Parameters
[in] id The id of the tls
[in] junction The junction controlled by this tls
[in] offset The offset of the plan
[in] type The algorithm type for the computed traffic light
Definition at line 63 of file NBOwnTLDef.cpp.
NBOwnTLDef::NBOwnTLDef (const std::string & id, SUMOTime offset, TrafficLightType type)
Constructor.
Parameters
[in] id The id of the tls
[in] offset The offset of the plan
[in] type The algorithm type for the computed traffic light
Definition at line 70 of file NBOwnTLDef.cpp.
NBOwnTLDef::~NBOwnTLDef ()
Destructor.
Definition at line 77 of file NBOwnTLDef.cpp.
Member Function Documentation
void NBTrafficLightDefinition::addControlledInnerEdges (const std::vector< std::string > & edges) inherited
Adds the given ids into the list of inner edges controlled by the tls.
Parameters
[in] edges The list of edge ids which shall be controlled despite lying with the jointly controlled node cluster
Definition at line 355 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myControlledInnerEdges.
Referenced by NIXMLTrafficLightsHandler::initTrafficLightLogic().
void NBTrafficLightDefinition::addNode (NBNode * node) virtual inherited
Adds a node to the traffic light logic.
Parameters
[in] node A further node that shall be controlled by the tls
Definition at line 335 of file NBTrafficLightDefinition.cpp.
References NBNode::addTrafficLight(), and NBTrafficLightDefinition::myControlledNodes.
Referenced by NBLoadedSUMOTLDef::addConnection(), NBLoadedTLDef::addToSignalGroup(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBNode::invalidateTLS(), and NBTrafficLightDefinition::NBTrafficLightDefinition().
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 53 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NLHandler::addParam(), SUMORouteHandler::addParam(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenDrive::loadNetwork(), and NIImporter_MATSim::EdgesHandler::myStartElement().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 59 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 67 of file Parameterised.cpp.
References Parameterised::myMap.
std::string NBOwnTLDef::addPedestrianPhases (NBTrafficLightLogic * logic, SUMOTime greenTime, std::string state, const std::vector< NBNode::Crossing > & crossings, const EdgeVector & fromEdges, const EdgeVector & toEdges) static
add 1 or 2 phases depending on the presence of pedestrian crossings
Definition at line 367 of file NBOwnTLDef.cpp.
References NBTrafficLightLogic::addStep(), patchStateForCrossings(), and TIME2STEPS.
Referenced by myCompute(), and NBLoadedSUMOTLDef::patchIfCrossingsAdded().
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
in,filled] cont The container to add this item to
Definition at line 121 of file Named.h.
References Named::StoringVisitor::add().
bool NBTrafficLightDefinition::amInvalid () const protected virtual inherited
Reimplemented in NBLoadedSUMOTLDef.
Definition at line 131 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myControlledLinks.
Referenced by NBTrafficLightDefinition::compute().
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 91 of file Parameterised.cpp.
References Parameterised::myMap.
void NBTrafficLightDefinition::collectAllLinks () protected inherited
helper method for use in NBOwnTLDef and NBLoadedSUMOTLDef
Definition at line 373 of file NBTrafficLightDefinition.cpp.
References NBEdge::Connection::fromLane, NBEdge::getConnectionsFromLane(), Named::getID(), NBEdge::getNumLanes(), NBEdge::mayBeTLSControlled(), NBTrafficLightDefinition::myControlledLinks, NBTrafficLightDefinition::myIncomingEdges, NBEdge::Connection::toEdge, NBEdge::Connection::toLane, and toString().
Referenced by NBLoadedSUMOTLDef::collectLinks(), and collectLinks().
void NBTrafficLightDefinition::collectEdges () protected inherited
Build the list of participating edges.
Definition at line 152 of file NBTrafficLightDefinition.cpp.
References Named::getID(), NBTrafficLightDefinition::myControlledInnerEdges, NBTrafficLightDefinition::myControlledNodes, NBTrafficLightDefinition::myEdgesWithin, and NBTrafficLightDefinition::myIncomingEdges.
Referenced by setParticipantsInformation(), and NBTrafficLightDefinition::setParticipantsInformation().
void NBOwnTLDef::collectLinks () protected virtual
Collects the links participating in this traffic light
Exceptions
ProcessError If a link could not be found.
See Also
NBTrafficLightDefinition::collectLinks
Implements NBTrafficLightDefinition.
Definition at line 447 of file NBOwnTLDef.cpp.
References NBTrafficLightDefinition::collectAllLinks().
Referenced by setParticipantsInformation().
void NBOwnTLDef::collectNodes () protected
Collects the nodes participating in this traffic light.
See Also
NBTrafficLightDefinition::collectNodes
Definition at line 443 of file NBOwnTLDef.cpp.
Referenced by setParticipantsInformation().
NBTrafficLightLogic * NBTrafficLightDefinition::compute (const NBEdgeCont & ec, OptionsCont & oc) inherited
Computes the traffic light logic.
Does some initialisation at first, then calls myCompute to finally build the tl-logic
Parameters
[in] ec The edge container in order to retrieve edge information
[in] oc The options container holding options needed during the building
Returns
The built logic (may be 0)
Definition at line 106 of file NBTrafficLightDefinition.cpp.
References Parameterised::addParameter(), NBTrafficLightDefinition::amInvalid(), NBTrafficLightDefinition::computeBrakingTime(), OptionsCont::getFloat(), Named::getID(), OptionsCont::getInt(), Parameterised::getMap(), OptionsCont::isSet(), NBTrafficLightDefinition::myCompute(), NBTrafficLightDefinition::myControlledNodes, and WRITE_WARNING.
Referenced by NBTrafficLightLogicCont::computeSingleLogic().
unsigned int NBTrafficLightDefinition::computeBrakingTime (SUMOReal minDecel) const protected inherited
Computes the time vehicles may need to brake.
This time depends on the maximum speed allowed on incoming junctions. It is computed as max_speed_allowed / minimum_vehicle_decleration
Definition at line 137 of file NBTrafficLightDefinition.cpp.
References NBContHelper::maxSpeed(), NBTrafficLightDefinition::myIncomingEdges, and SUMOReal.
Referenced by NBTrafficLightDefinition::compute().
SUMOReal NBOwnTLDef::computeUnblockedWeightedStreamNumber (const NBEdge *const e1, const NBEdge *const e2) protected
Returns how many streams outgoing from the edges can pass the junction without being blocked.
Parameters
[in] e1 The first edge
[in] e2 The second edge
Todo:
There are several magic numbers; describe
Definition at line 104 of file NBOwnTLDef.cpp.
References NBTrafficLightDefinition::foes(), NBEdge::getConnectionsFromLane(), NBNode::getDirection(), getDirectionalWeight(), NBEdge::getNumLanes(), NBEdge::getToNode(), NBEdge::getTurnDestination(), and SUMOReal.
Referenced by getBestCombination().
bool NBTrafficLightDefinition::foes (const NBEdge *const from1, const NBEdge *const to1, const NBEdge *const from2, const NBEdge *const to2) const inherited
Returns the information whether the given flows cross.
Parameters
[in] from1 The starting edge of the first stream
[in] to1 The ending edge of the first stream
[in] from2 The starting edge of the second stream
[in] to2 The ending edge of the second stream
Returns
Whether both stream are foes (cross)
Definition at line 312 of file NBTrafficLightDefinition.cpp.
References NBNode::foes(), and NBTrafficLightDefinition::myControlledNodes.
Referenced by computeUnblockedWeightedStreamNumber().
bool NBTrafficLightDefinition::forbids (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, bool regardNonSignalisedLowerPriority) const inherited
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
Parameters
[in] possProhibitedFrom The maybe prohibited connection's begin
[in] possProhibitedTo The maybe prohibited connection's end
[in] possProhibitorFrom The maybe prohibiting connection's begin
[in] possProhibitorTo The maybe prohibiting connection's end
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns
Whether the second flow prohibits the first one
See Also
forbids
Definition at line 235 of file NBTrafficLightDefinition.cpp.
References NBNode::foes(), NBNode::forbids(), NBEdge::getConnectedEdges(), and NBTrafficLightDefinition::myControlledNodes.
Referenced by NBTrafficLightDefinition::mustBrake(), and myCompute().
std::pair< NBEdge *, NBEdge * > NBOwnTLDef::getBestCombination (const EdgeVector & edges) protected
Returns the combination of two edges from the given which has most unblocked streams.
Parameters
[in] edges The list of edges to include in the computation
Returns
The two edges for which the weighted number of unblocked streams is the highest
Definition at line 131 of file NBOwnTLDef.cpp.
References computeUnblockedWeightedStreamNumber(), GeomHelper::getMinAngleDiff(), NUMERICAL_EPS, and SUMOReal.
Referenced by getBestPair().
std::pair< NBEdge *, NBEdge * > NBOwnTLDef::getBestPair (EdgeVector & incoming) protected
Returns the combination of two edges from the given which has most unblocked streams.
The chosen edges are removed from the given vector
Parameters
in,changed] incoming The list of edges which are participating in the logic
Returns
The two edges for which the weighted number of unblocked streams is the highest
Definition at line 158 of file NBOwnTLDef.cpp.
References getBestCombination(), and getToPrio().
Referenced by myCompute().
std::vector< std::string > NBTrafficLightDefinition::getControlledInnerEdges () const inherited
Retrieve the ids of edges explicitly controlled by the tls.
Definition at line 361 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myControlledInnerEdges.
Referenced by NIXMLTrafficLightsHandler::initTrafficLightLogic().
const NBConnectionVector& NBTrafficLightDefinition::getControlledLinks () const inline inherited
returns the controlled links (depends on previous call to collectLinks)
Definition at line 300 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::myControlledLinks.
Referenced by NBLoadedSUMOTLDef::NBLoadedSUMOTLDef().
SUMOReal NBOwnTLDef::getDirectionalWeight (LinkDirection dir) protected
Returns the weight of a stream given its direction.
Parameters
[in] dir The direction of the stream
Returns
This stream's weight
Todo:
There are several magic numbers; describe
Definition at line 87 of file NBOwnTLDef.cpp.
References LINKDIR_LEFT, LINKDIR_NODIR, LINKDIR_PARTLEFT, LINKDIR_PARTRIGHT, LINKDIR_RIGHT, LINKDIR_STRAIGHT, and LINKDIR_TURN.
Referenced by computeUnblockedWeightedStreamNumber().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 60 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), Named::StoringVisitor::add(), MSDetectorControl::add(), RORouteDef::addAlternative(), MSNet::addBusStop(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), NBNode::buildCrossings(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), NBNode::buildInnerEdges(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), NBNode::buildWalkingAreas(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBTrafficLightDefinition::collectEdges(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), NLDetectorBuilder::convUncontE2PosLength(), GUINet::createTLWrapper(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSE3Collector::enter(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSNet::getBusStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), PedestrianEdge< E, L, N >::getEffort(), NBEdge::getFirstNonPedestrianLane(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), AGStreet::getName(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPModel_Striping::getNextLane(), GUIVehicle::getParameterWindow(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), NBEdgeCont::ignoreFilterMatch(), MSActuatedTrafficLightLogic::init(), MSAgentbasedTrafficLightLogic::init(), MSTrafficLightLogic::init(), PedestrianEdge< E, L, N >::initPedestrianNetwork(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), RODFNet::isDestination(), RODFNet::isFalseSource(), RODFNet::isSource(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting(), myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Person::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), GUIViewTraffic::onGamingClick(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_JE2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSRightOfWayJunction::postloadInit(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBNodeCont::rename(), NBEdgeCont::rename(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), PCPolyContainer::save(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), NIXMLEdgesHandler::setNodes(), MSLink::setRequestInformation(), setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap_matchingEdgeLane(), TraCIServerAPI_Vehicle::vtdMap_matchingRoutePosition(), MSLCM_JE2013::wantsChange(), MSFCDExport::write(), MSEmissionExport::write(), MSInstantInductLoop::write(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const EdgeVector & NBTrafficLightDefinition::getIncomingEdges () const inherited
Returns the list of incoming edges (must be build first)
Returns
The edges which are incoming into the tls
Definition at line 367 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myIncomingEdges.
Referenced by myCompute().
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 107 of file Parameterised.h.
References Parameterised::myMap.
Referenced by NBTrafficLightDefinition::compute(), GUIVehicle::getParameterWindow(), and PCPolyContainer::save().
const std::vector<NBNode*>& NBTrafficLightDefinition::getNodes () const inline inherited
Returns the list of controlled nodes.
Returns
Controlled nodes
Definition at line 172 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::myControlledNodes.
Referenced by NIXMLTrafficLightsHandler::initTrafficLightLogic(), and NBNode::invalidateTLS().
SUMOTime NBTrafficLightDefinition::getOffset () inline inherited
Returns the offset.
Returns
Offset
Definition at line 324 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::myOffset.
Referenced by NBNode::invalidateTLS(), and NBLoadedSUMOTLDef::NBLoadedSUMOTLDef().
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 81 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSAgentbasedTrafficLightLogic::MSAgentbasedTrafficLightLogic(), and TraCIServerAPI_Vehicle::vtdMap_matchingNearest().
const std::string& NBTrafficLightDefinition::getProgramID () const inline inherited
Returns the ProgramID.
Returns
The ID of the program (subID)
Definition at line 308 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::mySubID.
Referenced by NIImporter_SUMO::addPhase(), NBTrafficLightLogicCont::computeSingleLogic(), NBTrafficLightLogicCont::extract(), NBTrafficLightLogicCont::insert(), myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), and NBLoadedSUMOTLDef::removeConnection().
int NBOwnTLDef::getToPrio (const NBEdge *const e) protected
Returns this edge's priority at the node it ends at.
Parameters
[in] e The edge to ask for his priority
Returns
The edge's priority at his destination node
Definition at line 81 of file NBOwnTLDef.cpp.
References NBEdge::getJunctionPriority(), and NBEdge::getToNode().
Referenced by getBestPair().
TrafficLightType NBTrafficLightDefinition::getType () const inline inherited
get the algorithm type (static etc..)
Definition at line 330 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::myType.
Referenced by NBNode::invalidateTLS(), and NBLoadedSUMOTLDef::NBLoadedSUMOTLDef().
bool NBTrafficLightDefinition::isLeftMover (const NBEdge *const from, const NBEdge *const to) const inherited
returns the information whether the given link is a left-mover
Parameters
[in] from The connection's start edge
[in] to The connection's end edge
Returns
Whether the connection is a left-mover
Definition at line 183 of file NBTrafficLightDefinition.cpp.
References NBNode::isLeftMover(), and NBTrafficLightDefinition::myControlledNodes.
Referenced by myCompute().
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 75 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), and TraCIServerAPI_Vehicle::vtdMap_matchingNearest().
bool NBTrafficLightDefinition::mustBrake (const NBEdge *const from, const NBEdge *const to) const inherited
Returns the information whether the described flow must let any other flow pass.
If the from/to connection passes only one junction (from is incoming into same node as to outgoes from) the node is asked whether the flow must brake- Otherwise true is returned (recheck!) "from" must be an incoming edge into one of the participating nodes!
Parameters
[in] from The connection's start edge
[in] to The connection's end edge
Returns
Whether the described connection must brake (has higher priorised foes)
Definition at line 199 of file NBTrafficLightDefinition.cpp.
References NBNode::mustBrake(), and NBTrafficLightDefinition::myControlledNodes.
Referenced by NBLoadedTLDef::mustBrake().
bool NBTrafficLightDefinition::mustBrake (const NBConnection & possProhibited, const NBConnection & possProhibitor, bool regardNonSignalisedLowerPriority) const inherited
Returns the information whether the described flow must let the other flow pass.
Parameters
[in] possProhibited The maybe prohibited connection
[in] possProhibitor The maybe prohibiting connection
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns
Whether the second flow prohibits the first one
See Also
forbids
Definition at line 225 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::forbids(), NBConnection::getFrom(), and NBConnection::getTo().
bool NBTrafficLightDefinition::mustBrake (const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, bool regardNonSignalisedLowerPriority) const inherited
Returns the information whether the described flow must let any other flow pass.
Parameters
[in] possProhibitedFrom The maybe prohibited connection's begin
[in] possProhibitedTo The maybe prohibited connection's end
[in] possProhibitorFrom The maybe prohibiting connection's begin
[in] possProhibitorTo The maybe prohibiting connection's end
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns
Whether the second flow prohibits the first one
See Also
forbids
Definition at line 213 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::forbids().
NBTrafficLightLogic * NBOwnTLDef::myCompute (const NBEdgeCont & ec, unsigned int brakingTimeSeconds) protected virtual
Computes the traffic light logic finally in dependence to the type.
Parameters
[in] ec The edge container
[in] brakingTime Duration a vehicle needs for braking in front of the tls
Returns
The computed logic
See Also
NBTrafficLightDefinition::myCompute
Implements NBTrafficLightDefinition.
Definition at line 187 of file NBOwnTLDef.cpp.
References addPedestrianPhases(), NBTrafficLightLogic::addStep(), NBTrafficLightLogic::closeBuilding(), NBTrafficLightDefinition::forbids(), getBestPair(), NBEdge::getConnectionsFromLane(), NBTrafficLightLogic::getDuration(), Named::getID(), NBTrafficLightDefinition::getIncomingEdges(), NBEdge::getNumLanes(), OptionsCont::getOptions(), NBTrafficLightDefinition::getProgramID(), NBEdge::getToNode(), isForbidden(), NBTrafficLightDefinition::isLeftMover(), NBEdge::isTurningDirectionAt(), NBEdge::mayBeTLSControlled(), NBTrafficLightDefinition::myControlledNodes, myHaveSinglePhase, NBTrafficLightDefinition::myOffset, NBTrafficLightDefinition::myType, TIME2STEPS, time2string(), and WRITE_WARNING.
std::string NBOwnTLDef::patchStateForCrossings (const std::string & state, const std::vector< NBNode::Crossing > & crossings, const EdgeVector & fromEdges, const EdgeVector & toEdges) static
compute phase state in regard to pedestrian crossings
Definition at line 395 of file NBOwnTLDef.cpp.
References NBNode::Crossing::edges, NBNode::getDirection(), isForbidden(), LINKDIR_PARTLEFT, LINKDIR_PARTRIGHT, LINKDIR_STRAIGHT, NBNode::mustBrakeForCrossing(), and NBNode::Crossing::node.
Referenced by addPedestrianPhases().
void NBOwnTLDef::remapRemoved (NBEdge * removed, const EdgeVector & incoming, const EdgeVector & outgoing) virtual
Replaces occurences of the removed edge in incoming/outgoing edges of all definitions.
Parameters
[in] removed The removed edge
[in] incoming The edges to use instead if an incoming edge was removed
[in] outgoing The edges to use instead if an outgoing edge was removed
See Also
NBTrafficLightDefinition::remapRemoved
Implements NBTrafficLightDefinition.
Definition at line 475 of file NBOwnTLDef.cpp.
void NBTrafficLightDefinition::removeNode (NBNode * node) virtual inherited
Removes the given node from the list of controlled nodes.
Parameters
[in] node The node that shall not be controlled by the tls any more
Definition at line 345 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myControlledNodes.
Referenced by NBNode::removeTrafficLight().
void NBOwnTLDef::replaceRemoved (NBEdge * removed, int removedLane, NBEdge * by, int byLane) protected virtual
Replaces a removed edge/lane.
Parameters
[in] removed The edge to replace
[in] removedLane The lane of this edge to replace
[in] by The edge to insert instead
[in] byLane This edge's lane to insert instead
See Also
NBTrafficLightDefinition::replaceRemoved
Implements NBTrafficLightDefinition.
Definition at line 480 of file NBOwnTLDef.cpp.
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 68 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::rename(), and NBEdgeCont::rename().
void NBOwnTLDef::setParticipantsInformation () virtual
Builds the list of participating nodes/edges/links.
See Also
NBTrafficLightDefinition::setParticipantsInformation
Reimplemented from NBTrafficLightDefinition.
Definition at line 453 of file NBOwnTLDef.cpp.
References NBTrafficLightDefinition::collectEdges(), collectLinks(), and collectNodes().
void NBTrafficLightDefinition::setProgramID (const std::string & programID) inline inherited
Sets the programID.
Parameters
[in] programID The new ID of the program (subID)
Definition at line 316 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::mySubID.
Referenced by NBTrafficLightLogicCont::insert().
void NBOwnTLDef::setSinglePhase () inline
Forces the definition not to compute an additional phase for left-movers.
Definition at line 119 of file NBOwnTLDef.h.
References myHaveSinglePhase.
void NBOwnTLDef::setTLControllingInformation (const NBEdgeCont & ec) const virtual
Informs edges about being controlled by a tls.
Parameters
[in] ec The container of edges
See Also
NBTrafficLightDefinition::setTLControllingInformation
Implements NBTrafficLightDefinition.
Definition at line 463 of file NBOwnTLDef.cpp.
References NBConnection::getFrom(), Named::getID(), NBTrafficLightDefinition::myControlledLinks, and NBEdge::setControllingTLInformation().
virtual void NBTrafficLightDefinition::shiftTLConnectionLaneIndex (NBEdge * edge, int offset) inline virtual inherited
patches (loaded) signal plans by modifying lane indices
Reimplemented in NBLoadedSUMOTLDef.
Definition at line 280 of file NBTrafficLightDefinition.h.
References UNUSED_PARAMETER.
Field Documentation
const std::string NBTrafficLightDefinition::DefaultProgramID = "0" static inherited
Definition at line 78 of file NBTrafficLightDefinition.h.
Referenced by NIXMLTrafficLightsHandler::initTrafficLightLogic().
std::set<std::string> NBTrafficLightDefinition::myControlledInnerEdges protected inherited
Set of inner edges that shall be controlled, though.
Definition at line 384 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::addControlledInnerEdges(), NBTrafficLightDefinition::collectEdges(), and NBTrafficLightDefinition::getControlledInnerEdges().
NBConnectionVector NBTrafficLightDefinition::myControlledLinks protected inherited
The list of controlled links.
Definition at line 381 of file NBTrafficLightDefinition.h.
Referenced by NBLoadedSUMOTLDef::addConnection(), NBLoadedSUMOTLDef::amInvalid(), NBTrafficLightDefinition::amInvalid(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectLinks(), NBLoadedTLDef::collectLinks(), NBTrafficLightDefinition::getControlledLinks(), NBLoadedSUMOTLDef::NBLoadedSUMOTLDef(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), NBLoadedSUMOTLDef::removeConnection(), setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), and NBLoadedSUMOTLDef::shiftTLConnectionLaneIndex().
std::vector<NBNode*> NBTrafficLightDefinition::myControlledNodes protected inherited
The container with participating nodes.
Definition at line 372 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::addNode(), NBLoadedSUMOTLDef::amInvalid(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectLinks(), NBLoadedTLDef::collectNodes(), NBTrafficLightDefinition::compute(), NBTrafficLightDefinition::foes(), NBTrafficLightDefinition::forbids(), NBTrafficLightDefinition::getNodes(), NBTrafficLightDefinition::isLeftMover(), NBTrafficLightDefinition::mustBrake(), myCompute(), NBTrafficLightDefinition::NBTrafficLightDefinition(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), and NBTrafficLightDefinition::removeNode().
EdgeVector NBTrafficLightDefinition::myEdgesWithin protected inherited
The list of edges within the area controlled by the tls.
Definition at line 378 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::collectEdges().
bool NBOwnTLDef::myHaveSinglePhase private
Whether left-mover should not have an additional phase.
Definition at line 230 of file NBOwnTLDef.h.
Referenced by myCompute(), and setSinglePhase().
std::string Named::myID protected inherited
The name of the object.
Definition at line 128 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), NBNode::computeNodeShape(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSAgentbasedTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSCalibrator::VehicleRemover::notifyEnter(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), RORouteDef::repairCurrentRoute(), Named::setID(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
EdgeVector NBTrafficLightDefinition::myIncomingEdges protected inherited
The list of incoming edges.
Definition at line 375 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::collectAllLinks(), NBTrafficLightDefinition::collectEdges(), NBLoadedTLDef::collectLinks(), NBTrafficLightDefinition::computeBrakingTime(), and NBTrafficLightDefinition::getIncomingEdges().
SUMOTime NBTrafficLightDefinition::myOffset protected inherited
The offset in the program.
Definition at line 390 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::getOffset(), myCompute(), NBLoadedTLDef::myCompute(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), NBLoadedSUMOTLDef::removeConnection(), and NBLoadedSUMOTLDef::setOffset().
std::string NBTrafficLightDefinition::mySubID protected inherited
The tls program's subid.
Definition at line 387 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::getProgramID(), and NBTrafficLightDefinition::setProgramID().
TrafficLightType NBTrafficLightDefinition::myType protected inherited
The algorithm type for the traffic light.
Definition at line 393 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::getType(), myCompute(), NBLoadedTLDef::myCompute(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), and NBLoadedSUMOTLDef::removeConnection().
The documentation for this class was generated from the following files:
NBOwnTLDef.h
NBOwnTLDef.cpp