SUMO - Simulation of Urban MObility: DijkstraRouterTT_ByProxi< E, V, PF > Class Template Reference
DijkstraRouterTT_ByProxi< E, V, PF > Class Template Reference
#include <DijkstraRouterTT.h>
Public Types
typedef SUMOReal(* Operation)(const E *const, const V *const, SUMOReal)
Type of the function that is used to retrieve the edge effort.
Public Member Functions
void buildPathFrom (EdgeInfo *rbegin, std::vector< const E * > &edges)
Builds the path from marked edges.
virtual void compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > &into)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
DijkstraRouterTT_ByProxi (size_t noE, bool unbuildIsWarningOnly, Operation operation)
void endQuery (int visits)
SUMOReal getEffort (const E *const e, const V *const v, SUMOReal t) const
void init ()
virtual void prepare (const E *, const V *, bool)
SUMOReal recomputeCosts (const std::vector< const E * > &edges, const V *const v, SUMOTime msTime) const
void startQuery ()
Protected Attributes
EdgeInfoByTTComparator myComparator
std::vector< EdgeInfo > myEdgeInfos
The container of edge information.
MsgHandler *const myErrorMsgHandler
the handler for routing errors
std::vector< EdgeInfo * > myFound
list of visited Edges (for resetting)
std::vector< EdgeInfo * > myFrontierList
A container for reusage of the min edge heap.
Private Attributes
Operation myOperation
The object's operation to perform.
Detailed Description
template<class E, class V, class PF>
class DijkstraRouterTT_ByProxi< E, V, PF >
Definition at line 263 of file DijkstraRouterTT.h.
Member Typedef Documentation
template<class E, class V, class PF> typedef SUMOReal(* DijkstraRouterTT_ByProxi< E, V, PF >::Operation)(const E *const, const V *const, SUMOReal)
Type of the function that is used to retrieve the edge effort.
Definition at line 266 of file DijkstraRouterTT.h.
Constructor & Destructor Documentation
template<class E, class V, class PF> DijkstraRouterTT_ByProxi< E, V, PF >::DijkstraRouterTT_ByProxi (size_t noE, bool unbuildIsWarningOnly, Operation operation) inline
Definition at line 268 of file DijkstraRouterTT.h.
Member Function Documentation
template<class E, class V, class PF> void DijkstraRouterTTBase< E, V, PF >::buildPathFrom (EdgeInfo * rbegin, std::vector< const E * > & edges) inline inherited
Builds the path from marked edges.
Definition at line 237 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> virtual void DijkstraRouterTTBase< E, V, PF >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > & into) inline virtual inherited
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Implements SUMOAbstractRouter< E, V >.
Definition at line 151 of file DijkstraRouterTT.h.
template<class E, class V> void SUMOAbstractRouter< E, V >::endQuery (int visits) inline inherited
Definition at line 90 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> SUMOReal DijkstraRouterTT_ByProxi< E, V, PF >::getEffort (const E *const e, const V *const v, SUMOReal t) const inline virtual
Implements DijkstraRouterTTBase< E, V, PF >.
Definition at line 272 of file DijkstraRouterTT.h.
template<class E, class V, class PF> void DijkstraRouterTTBase< E, V, PF >::init () inline inherited
Definition at line 136 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V> virtual void SUMOAbstractRouter< E, V >::prepare (const E * , const V * , bool) inline virtual inherited
Definition at line 81 of file SUMOAbstractRouter.h.
template<class E, class V, class PF> SUMOReal DijkstraRouterTTBase< E, V, PF >::recomputeCosts (const std::vector< const E * > & edges, const V *const v, SUMOTime msTime) const inline virtual inherited
Implements SUMOAbstractRouter< E, V >.
Definition at line 223 of file DijkstraRouterTT.h.
template<class E, class V> void SUMOAbstractRouter< E, V >::startQuery () inline inherited
Definition at line 85 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
Field Documentation
template<class E, class V, class PF> EdgeInfoByTTComparator DijkstraRouterTTBase< E, V, PF >::myComparator protected inherited
Definition at line 255 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> std::vector<EdgeInfo> DijkstraRouterTTBase< E, V, PF >::myEdgeInfos protected inherited
The container of edge information.
Definition at line 248 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::DijkstraRouterTTBase().
template<class E, class V, class PF> MsgHandler* const DijkstraRouterTTBase< E, V, PF >::myErrorMsgHandler protected inherited
the handler for routing errors
Definition at line 258 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> std::vector<EdgeInfo*> DijkstraRouterTTBase< E, V, PF >::myFound protected inherited
list of visited Edges (for resetting)
Definition at line 253 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::init().
template<class E, class V, class PF> std::vector<EdgeInfo*> DijkstraRouterTTBase< E, V, PF >::myFrontierList protected inherited
A container for reusage of the min edge heap.
Definition at line 251 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::init().
template<class E, class V, class PF> Operation DijkstraRouterTT_ByProxi< E, V, PF >::myOperation private
The object's operation to perform.
Definition at line 278 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTT_ByProxi< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::getEffort().
The documentation for this class was generated from the following file:
DijkstraRouterTT.h