SUMO - Simulation of Urban MObility: ROGawronCalculator Class Reference
ROGawronCalculator Class Reference
Cost calculation with Gawron's method.
#include <ROCostCalculator.h>
Public Member Functions
void calculateProbabilities (std::vector< RORoute * > alternatives, const ROVehicle *const veh, const SUMOTime time)
calculate the probabilities
unsigned int getMaxRouteNumber () const
bool keepRoutes () const
ROGawronCalculator (const SUMOReal beta, const SUMOReal a)
Constructor.
void setCosts (RORoute *route, const SUMOReal costs, const bool isActive=false) const
bool skipRouteCalculation () const
virtual ~ROGawronCalculator ()
Destructor.
Static Public Member Functions
static void cleanup ()
static ROCostCalculator & getCalculator ()
Private Member Functions
SUMOReal gawronF (const SUMOReal pdr, const SUMOReal pds, const SUMOReal x) const
Performs the gawron - f() function From "Dynamic User Equilibria...".
SUMOReal gawronG (const SUMOReal a, const SUMOReal x) const
Performs the gawron - g() function From "Dynamic User Equilibria...".
ROGawronCalculator & operator= (const ROGawronCalculator &s)
invalidated assignment operator
Private Attributes
const SUMOReal myA
gawron a - value
const SUMOReal myBeta
gawron beta - value
Detailed Description
Cost calculation with Gawron's method.
Definition at line 102 of file ROCostCalculator.h.
Constructor & Destructor Documentation
ROGawronCalculator::ROGawronCalculator (const SUMOReal beta, const SUMOReal a)
Constructor.
Definition at line 89 of file ROCostCalculator.cpp.
ROGawronCalculator::~ROGawronCalculator () virtual
Destructor.
Definition at line 93 of file ROCostCalculator.cpp.
Member Function Documentation
void ROGawronCalculator::calculateProbabilities (std::vector< RORoute * > alternatives, const ROVehicle *const veh, const SUMOTime time) virtual
calculate the probabilities
Implements ROCostCalculator.
Definition at line 107 of file ROCostCalculator.cpp.
References gawronF(), RORoute::getCosts(), RORoute::getProbability(), ISNAN(), MAX2(), MIN2(), RORoute::setProbability(), and SUMOReal.
void ROCostCalculator::cleanup () static inherited
Definition at line 83 of file ROCostCalculator.cpp.
References ROCostCalculator::myInstance.
Referenced by computeRoutes().
SUMOReal ROGawronCalculator::gawronF (const SUMOReal pdr, const SUMOReal pds, const SUMOReal x) const private
Performs the gawron - f() function From "Dynamic User Equilibria...".
Definition at line 135 of file ROCostCalculator.cpp.
References gawronG(), max, and myA.
Referenced by calculateProbabilities().
SUMOReal ROGawronCalculator::gawronG (const SUMOReal a, const SUMOReal x) const private
Performs the gawron - g() function From "Dynamic User Equilibria...".
Definition at line 145 of file ROCostCalculator.cpp.
References max, and SUMOReal.
Referenced by gawronF().
ROCostCalculator & ROCostCalculator::getCalculator () static inherited
Definition at line 69 of file ROCostCalculator.cpp.
References OptionsCont::getFloat(), OptionsCont::getOptions(), OptionsCont::getString(), and ROCostCalculator::myInstance.
Referenced by RORouteDef::addAlternative(), and RORouteDef::preComputeCurrentRoute().
unsigned int ROCostCalculator::getMaxRouteNumber () const inline inherited
Definition at line 64 of file ROCostCalculator.h.
References ROCostCalculator::myMaxRouteNumber.
Referenced by RORouteDef::addAlternative().
bool ROCostCalculator::keepRoutes () const inline inherited
Definition at line 68 of file ROCostCalculator.h.
References ROCostCalculator::myKeepRoutes.
Referenced by RORouteDef::addAlternative().
ROGawronCalculator& ROGawronCalculator::operator= (const ROGawronCalculator & s) private
invalidated assignment operator
void ROGawronCalculator::setCosts (RORoute * route, const SUMOReal costs, const bool isActive = false) const virtual
Implements ROCostCalculator.
Definition at line 97 of file ROCostCalculator.cpp.
References RORoute::getCosts(), myBeta, RORoute::setCosts(), and SUMOReal.
bool ROCostCalculator::skipRouteCalculation () const inline inherited
Definition at line 72 of file ROCostCalculator.h.
References ROCostCalculator::mySkipRouteCalculation.
Field Documentation
const SUMOReal ROGawronCalculator::myA private
gawron a - value
Definition at line 129 of file ROCostCalculator.h.
Referenced by gawronF().
const SUMOReal ROGawronCalculator::myBeta private
gawron beta - value
Definition at line 126 of file ROCostCalculator.h.
Referenced by setCosts().
The documentation for this class was generated from the following files:
ROCostCalculator.h
ROCostCalculator.cpp