Veins Framework: ConstMappingIterator Class Reference
ConstMappingIterator Class Reference abstract
Defines an const iterator for a ConstMapping which is able to iterate over the Mapping.
#include <MappingBase.h>
Public Types
typedef Argument::mapped_type argument_value_t
typedef Argument::mapped_type_cref argument_value_cref_t
Public Member Functions
virtual ~ConstMappingIterator ()
virtual const Argument & getNextPosition () const =0
Returns the position the next call to "next()" of this Iterator would iterate to.
virtual void jumpTo (const Argument &pos)=0
Lets the iterator point to the passed position.
virtual void jumpToBegin ()=0
Lets the iterator point to the begin of the mapping.
virtual void iterateTo (const Argument &pos)=0
Iterates to the specified position.
virtual void next ()=0
Iterates to the next position of the Mapping.
virtual bool inRange () const =0
Returns true if the current position of the iterator is in range of the function.
virtual bool hasNext () const =0
Returns true if the iterator has a next value it can iterate to on a call to "next()".
virtual const Argument & getPosition () const =0
Returns the current position of the iterator.
virtual argument_value_t getValue () const =0
Returns the value of the Mapping at the current position.
Detailed Description
Defines an const iterator for a ConstMapping which is able to iterate over the Mapping.
Iterators provide a fast way to iterate over every "entry" or important position of a Mapping. They also provide constant complexity for accessing the Mapping at the position of the Iterator.
Every implementation of an mapping-Iterator provides the same ordering when iterating over a Mapping. This is that, if the iterator is increased, the position of the entry it points to has to be also "increased". Which means that the new position has to be compared bigger than the previous position (see class Argument for comparison of positions).
"Const" means that you can not change the values of the underlying Mapping with this iterator.
Author
Karl Wessel
Definition at line 576 of file MappingBase.h.
Member Typedef Documentation
typedef Argument::mapped_type_cref ConstMappingIterator::argument_value_cref_t
Definition at line 579 of file MappingBase.h.
typedef Argument::mapped_type ConstMappingIterator::argument_value_t
Definition at line 578 of file MappingBase.h.
Constructor & Destructor Documentation
virtual ConstMappingIterator::~ConstMappingIterator () inline virtual
Definition at line 581 of file MappingBase.h.
 {}
Member Function Documentation
virtual const Argument& ConstMappingIterator::getNextPosition () const pure virtual
Returns the position the next call to "next()" of this Iterator would iterate to.
Implemented in SimpleConstMappingIterator, MultiDimMappingIterator< Interpolator >, MultiDimMappingIterator< Linear >, ConstMappingIteratorWrapper, RSAMConstMappingIterator, LinearIntplMappingIterator, TimeMappingIterator< Interpolator >, and BaseFilteredIterator< MappingIterator >.
Referenced by SNRThresholdDecider::checkIfAboveThreshold(), MappingUtils::findMin(), ConstMappingIteratorWrapper::getNextPosition(), MappingUtils::iterateToNext(), and MultiDimMappingIterator< Linear >::updateNextPosition().
virtual const Argument& ConstMappingIterator::getPosition () const pure virtual
Returns the current position of the iterator.
Implemented in SimpleConstMappingIterator, MultiDimMappingIterator< Interpolator >, MultiDimMappingIterator< Linear >, ConstMappingIteratorWrapper, RSAMConstMappingIterator, LinearIntplMappingIterator, TimeMappingIterator< Interpolator >, and BaseFilteredIterator< MappingIterator >.
Referenced by MappingUtils::applyElementWiseOperator(), SNRThresholdDecider::checkIfAboveThreshold(), MappingUtils::createCompatibleMapping(), FilledUpMapping::FilledUpMapping(), MappingUtils::findMin(), LinearIntplMappingIterator::getPosition(), ConstMappingIteratorWrapper::getPosition(), MappingUtils::iterateToNext(), MultiDimMappingIterator< Linear >::jumpToBegin(), LinearIntplMappingIterator::LinearIntplMappingIterator(), MultiDimMappingIterator< Linear >::MultiDimMappingIterator(), MultiDimMappingIterator< Linear >::next(), ConstMapping::print(), and MultiDimMappingIterator< Linear >::updateNextPosition().
virtual argument_value_t ConstMappingIterator::getValue () const pure virtual
Returns the value of the Mapping at the current position.
The complexity of this method should be constant for every implementation.
Implemented in SimpleConstMappingIterator, MultiDimMappingIterator< Interpolator >, MultiDimMappingIterator< Linear >, ConstMappingIteratorWrapper, RSAMConstMappingIterator, LinearIntplMappingIterator, TimeMappingIterator< Interpolator >, and BaseFilteredIterator< MappingIterator >.
Referenced by MappingUtils::applyElementWiseOperator(), SNRThresholdDecider::checkIfAboveThreshold(), Decider80211p::checkIfSignalOk(), FilledUpMapping::FilledUpMapping(), MappingUtils::findMax(), MappingUtils::findMin(), LinearIntplMappingIterator::getValue(), ConstMappingIteratorWrapper::getValue(), MultiDimMappingIterator< Linear >::getValue(), and ConstMapping::print().
virtual bool ConstMappingIterator::hasNext () const pure virtual
Returns true if the iterator has a next value it can iterate to on a call to "next()".
Implemented in SimpleConstMappingIterator, MultiDimMappingIterator< Interpolator >, MultiDimMappingIterator< Linear >, ConstMappingIteratorWrapper, RSAMConstMappingIterator, LinearIntplMappingIterator, TimeMappingIterator< Interpolator >, and BaseFilteredIterator< MappingIterator >.
Referenced by SNRThresholdDecider::checkIfAboveThreshold(), MappingUtils::createCompatibleMapping(), FilledUpMapping::FilledUpMapping(), MappingUtils::findMax(), MappingUtils::findMin(), ConstMappingIteratorWrapper::hasNext(), MultiDimMappingIterator< Linear >::hasNext(), MappingUtils::iterateToNext(), MultiDimMappingIterator< Linear >::next(), ConstMapping::print(), and MultiDimMappingIterator< Linear >::updateNextPosition().
virtual bool ConstMappingIterator::inRange () const pure virtual
Returns true if the current position of the iterator is in range of the function.
This method should be used as end-condition when iterating over the function with the "next()" method.
Implemented in SimpleConstMappingIterator, MultiDimMappingIterator< Interpolator >, MultiDimMappingIterator< Linear >, ConstMappingIteratorWrapper, RSAMConstMappingIterator, LinearIntplMappingIterator, TimeMappingIterator< Interpolator >, and BaseFilteredIterator< MappingIterator >.
Referenced by MappingUtils::applyElementWiseOperator(), MappingUtils::createCompatibleMapping(), FilledUpMapping::FilledUpMapping(), MappingUtils::findMax(), MappingUtils::findMin(), ConstMappingIteratorWrapper::inRange(), MultiDimMappingIterator< Linear >::inRange(), and ConstMapping::print().
virtual void ConstMappingIterator::iterateTo (const Argument & pos) pure virtual
Iterates to the specified position.
This method should be used if the new position is near the current position. Furthermore the new position has to be compared bigger than the old position.
Implemented in SimpleConstMappingIterator, MultiDimMappingIterator< Interpolator >, MultiDimMappingIterator< Linear >, ConstMappingIteratorWrapper, RSAMConstMappingIterator, LinearIntplMappingIterator, TimeMappingIterator< Interpolator >, and BaseFilteredIterator< MappingIterator >.
Referenced by MappingUtils::applyElementWiseOperator(), SNRThresholdDecider::checkIfAboveThreshold(), MappingUtils::findMin(), LinearIntplMappingIterator::iterateTo(), ConstMappingIteratorWrapper::iterateTo(), MultiDimMappingIterator< Linear >::iterateTo(), MappingUtils::iterateToNext(), and RSAMConstMappingIterator::next().
virtual void ConstMappingIterator::jumpTo (const Argument & pos) pure virtual
Lets the iterator point to the passed position.
The passed new position can be at arbitrary places.
Implemented in SimpleConstMappingIterator, MultiDimMappingIterator< Interpolator >, MultiDimMappingIterator< Linear >, ConstMappingIteratorWrapper, RSAMConstMappingIterator, LinearIntplMappingIterator, TimeMappingIterator< Interpolator >, and BaseFilteredIterator< MappingIterator >.
Referenced by MappingUtils::applyElementWiseOperator(), LinearIntplMappingIterator::jumpTo(), ConstMappingIteratorWrapper::jumpTo(), MultiDimMappingIterator< Linear >::jumpTo(), RSAMConstMappingIterator::jumpToBegin(), and MultiDimMappingIterator< Linear >::updateSubIterator().
virtual void ConstMappingIterator::jumpToBegin () pure virtual
Lets the iterator point to the begin of the mapping.
The beginning of the mapping depends on the implementation. With an implementation based on a number of key-entries, this could be the key entry with the smallest position (see class Argument for ordering of positions).
Implemented in SimpleConstMappingIterator, MultiDimMappingIterator< Interpolator >, MultiDimMappingIterator< Linear >, ConstMappingIteratorWrapper, RSAMConstMappingIterator, LinearIntplMappingIterator, TimeMappingIterator< Interpolator >, and BaseFilteredIterator< MappingIterator >.
Referenced by ConstMappingIteratorWrapper::jumpToBegin(), and MultiDimMappingIterator< Linear >::updateSubIterator().
virtual void ConstMappingIterator::next () pure virtual
Iterates to the next position of the Mapping.
The next position depends on the implementation of the Mapping. With an implementation based on a number of key-entries this probably would be the next bigger key-entry.
Implemented in SimpleConstMappingIterator, MultiDimMappingIterator< Interpolator >, MultiDimMappingIterator< Linear >, ConstMappingIteratorWrapper, RSAMConstMappingIterator, LinearIntplMappingIterator, TimeMappingIterator< Interpolator >, and BaseFilteredIterator< MappingIterator >.
Referenced by SNRThresholdDecider::checkIfAboveThreshold(), Decider80211p::checkIfSignalOk(), MappingUtils::createCompatibleMapping(), FilledUpMapping::FilledUpMapping(), MappingUtils::findMax(), MappingUtils::findMin(), MappingUtils::iterateToNext(), ConstMappingIteratorWrapper::next(), MultiDimMappingIterator< Linear >::next(), and ConstMapping::print().
The documentation for this class was generated from the following file:
MappingBase.h