Veins Framework: Veins::TraCIBuffer Class Reference
Veins::TraCIBuffer Class Reference
Byte-buffer that stores values in TraCI byte-order.
#include <TraCIBuffer.h>
Public Member Functions
TraCIBuffer ()
TraCIBuffer (std::string buf)
template<typename T >
T read ()
template<typename T >
void write (T inv)
template<typename T >
T read (T &out)
template<typename T >
TraCIBuffer & operator>> (T &out)
template<typename T >
TraCIBuffer & operator<< (const T &inv)
bool eof () const
void set (std::string buf)
void clear ()
std::string str () const
std::string hexStr () const
template<>
void write (std::string inv)
template<>
std::string read ()
template<>
void write (TraCICoord inv)
template<>
TraCICoord read ()
Private Attributes
std::string buf
size_t buf_index
Detailed Description
Byte-buffer that stores values in TraCI byte-order.
Definition at line 18 of file TraCIBuffer.h.
Constructor & Destructor Documentation
Veins::TraCIBuffer::TraCIBuffer ()
Definition at line 10 of file TraCIBuffer.cc.
                          : buf() {
         buf_index = 0;
 }
Veins::TraCIBuffer::TraCIBuffer (std::string buf)
Definition at line 14 of file TraCIBuffer.cc.
                                       : buf(buf) {
         buf_index = 0;
 }
Member Function Documentation
void Veins::TraCIBuffer::clear ()
Definition at line 27 of file TraCIBuffer.cc.
{
         set("");
 }
bool Veins::TraCIBuffer::eof () const
Definition at line 18 of file TraCIBuffer.cc.
Referenced by Veins::TraCICommandInterface::addPoi(), Veins::TraCICommandInterface::addPolygon(), Veins::TraCICommandInterface::addVehicle(), Veins::TraCICommandInterface::Vehicle::changeRoute(), Veins::TraCICommandInterface::Vehicle::changeVehicleRoute(), Veins::TraCICommandInterface::genericGetCoord(), Veins::TraCICommandInterface::genericGetCoordList(), Veins::TraCICommandInterface::genericGetDouble(), Veins::TraCICommandInterface::genericGetInt(), Veins::TraCICommandInterface::genericGetString(), Veins::TraCICommandInterface::genericGetStringList(), Veins::TraCICommandInterface::getDistance(), Veins::TraCICommandInterface::getVersion(), Veins::TraCIScenarioManager::init_traci(), Veins::TraCICommandInterface::Vehicle::newRoute(), read(), Veins::TraCICommandInterface::GuiView::setBoundary(), Veins::TraCICommandInterface::Vehicle::setParking(), Veins::TraCICommandInterface::Trafficlight::setPhaseIndex(), Veins::TraCICommandInterface::Trafficlight::setProgram(), Veins::TraCICommandInterface::GuiView::setScheme(), Veins::TraCICommandInterface::Polygon::setShape(), Veins::TraCICommandInterface::Vehicle::setSpeed(), Veins::TraCICommandInterface::Vehicle::setSpeedMode(), Veins::TraCICommandInterface::GuiView::setZoom(), Veins::TraCICommandInterface::Vehicle::slowDown(), Veins::TraCICommandInterface::Vehicle::stopAt(), Veins::TraCIScenarioManager::subscribeToVehicleVariables(), Veins::TraCICommandInterface::GuiView::takeScreenshot(), and Veins::TraCIScenarioManager::unsubscribeFromVehicleVariables().
{
         return buf_index == buf.length();
 }
std::string Veins::TraCIBuffer::hexStr () const
Definition at line 35 of file TraCIBuffer.cc.
{
         std::stringstream ss;
         for (std::string::const_iterator i = buf.begin() + buf_index; i != buf.end(); ++i) {
                 if (i != buf.begin()) ss << " ";
                 ss << std::hex << std::setw(2) << std::setfill('0') << (int)(uint8_t)*i;
         }
         return ss.str();
 }
template<typename T > TraCIBuffer& Veins::TraCIBuffer::operator<< (const T & inv) inline
Definition at line 66 of file TraCIBuffer.h.
{
                         write(inv);
                         return *this;
                 }
template<typename T > TraCIBuffer& Veins::TraCIBuffer::operator>> (T & out) inline
Definition at line 61 of file TraCIBuffer.h.
{
                         out = read<T>();
                         return *this;
                 }
template<typename T > T Veins::TraCIBuffer::read () inline
Definition at line 23 of file TraCIBuffer.h.
{
                         T buf_to_return;
                         unsigned char *p_buf_to_return = reinterpret_cast<unsigned char*>(&buf_to_return);
                         if (isBigEndian()) {
                                 for (size_t i=0; i<sizeof(buf_to_return); ++i) {
                                         if (eof()) throw cRuntimeError("Attempted to read past end of byte buffer");
                                         p_buf_to_return[i] = buf[buf_index++];
                                 }
                         } else {
                                 for (size_t i=0; i<sizeof(buf_to_return); ++i) {
                                         if (eof()) throw cRuntimeError("Attempted to read past end of byte buffer");
                                         p_buf_to_return[sizeof(buf_to_return)-1-i] = buf[buf_index++];
                                 }
                         }
                         return buf_to_return;
                 }
std::string Veins::TraCIBuffer::read ()
Definition at line 50 of file TraCIBuffer.cc.
{
         uint32_t length = read<uint32_t> ();
         if (length == 0) return std::string();
         char obuf[length + 1];
         for (size_t i = 0; i < length; ++i) read<char> (obuf[i]);
         obuf[length] = 0;
         return std::string(obuf, length);
 }
template<typename T > T Veins::TraCIBuffer::read (T & out) inline
Definition at line 56 of file TraCIBuffer.h.
{
                         out = read<T>();
                         return out;
                 }
TraCICoord Veins::TraCIBuffer::read ()
Definition at line 67 of file TraCIBuffer.cc.
{
         uint8_t posType = read<uint8_t>();
         ASSERT(posType == POSITION_2D);
         TraCICoord p;
         p.x = read<double>();
         p.y = read<double>();
         return p;
 }
void Veins::TraCIBuffer::set (std::string buf)
Definition at line 22 of file TraCIBuffer.cc.
Referenced by clear().
{
         this->buf = buf;
         buf_index = 0;
 }
std::string Veins::TraCIBuffer::str () const
Definition at line 31 of file TraCIBuffer.cc.
Referenced by Veins::makeTraCICommand(), and Veins::TraCIConnection::sendMessage().
{
         return buf;
 }
template<typename T > void Veins::TraCIBuffer::write (T inv) inline
Definition at line 42 of file TraCIBuffer.h.
Referenced by operator<<().
{
                         unsigned char *p_buf_to_send = reinterpret_cast<unsigned char*>(&inv);
                         if (isBigEndian()) {
                                 for (size_t i=0; i<sizeof(inv); ++i) {
                                         buf += p_buf_to_send[i];
                                 }
                         } else {
                                 for (size_t i=0; i<sizeof(inv); ++i) {
                                         buf += p_buf_to_send[sizeof(inv)-1-i];
                                 }
                         }
                 }
void Veins::TraCIBuffer::write (std::string inv)
Definition at line 44 of file TraCIBuffer.cc.
{
         uint32_t length = inv.length();
         write<uint32_t> (length);
         for (size_t i = 0; i < length; ++i) write<char> (inv[i]);
 }
void Veins::TraCIBuffer::write (TraCICoord inv)
Definition at line 61 of file TraCIBuffer.cc.
{
         write<uint8_t>(POSITION_2D);
         write<double>(inv.x);
         write<double>(inv.y);
 }
Member Data Documentation
std::string Veins::TraCIBuffer::buf private
Definition at line 78 of file TraCIBuffer.h.
Referenced by eof(), hexStr(), set(), and str().
size_t Veins::TraCIBuffer::buf_index private
Definition at line 79 of file TraCIBuffer.h.
Referenced by eof(), hexStr(), read(), set(), and TraCIBuffer().
The documentation for this class was generated from the following files:
TraCIBuffer.h
TraCIBuffer.cc