Veins Framework: Veins::TraCIScenarioManagerAccess Class Reference
Veins::TraCIScenarioManagerAccess Class Reference
#include <TraCIScenarioManager.h>
Public Member Functions
TraCIScenarioManager * get ()
Detailed Description
Definition at line 186 of file TraCIScenarioManager.h.
Member Function Documentation
TraCIScenarioManager* Veins::TraCIScenarioManagerAccess::get () inline
Definition at line 189 of file TraCIScenarioManager.h.
Referenced by Veins::TraCIMobility::getManager(), Veins::TraCIScreenRecorder::handleMessage(), Veins::AnnotationManager::hide(), and Veins::AnnotationManager::show().
{
                         return FindModule<TraCIScenarioManager*>::findGlobalModule();
                 };
The documentation for this class was generated from the following file:
TraCIScenarioManager.h