Veins Framework: WaveShortMessage Class Reference
WaveShortMessage Class Reference
Class generated from veins/modules/messages/WaveShortMessage.msg:27 by nedtool.
#include <WaveShortMessage_m.h>
Public Member Functions
WaveShortMessage (const char *name=NULL, int kind=0)
WaveShortMessage (const WaveShortMessage &other)
virtual ~WaveShortMessage ()
WaveShortMessage & operator= (const WaveShortMessage &other)
virtual WaveShortMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getWsmVersion () const
virtual void setWsmVersion (int wsmVersion)
virtual int getSecurityType () const
virtual void setSecurityType (int securityType)
virtual int getChannelNumber () const
virtual void setChannelNumber (int channelNumber)
virtual int getDataRate () const
virtual void setDataRate (int dataRate)
virtual int getPriority () const
virtual void setPriority (int priority)
virtual int getPsid () const
virtual void setPsid (int psid)
virtual const char * getPsc () const
virtual void setPsc (const char *psc)
virtual int getWsmLength () const
virtual void setWsmLength (int wsmLength)
virtual const char * getWsmData () const
virtual void setWsmData (const char *wsmData)
virtual int getSenderAddress () const
virtual void setSenderAddress (int senderAddress)
virtual int getRecipientAddress () const
virtual void setRecipientAddress (int recipientAddress)
virtual int getSerial () const
virtual void setSerial (int serial)
virtual Coord & getSenderPos ()
virtual const Coord & getSenderPos () const
virtual void setSenderPos (const Coord &senderPos)
virtual simtime_t getTimestamp () const
virtual void setTimestamp (simtime_t timestamp)
Protected Member Functions
bool operator== (const WaveShortMessage &)
Protected Attributes
int wsmVersion_var
int securityType_var
int channelNumber_var
int dataRate_var
int priority_var
int psid_var
opp_string psc_var
int wsmLength_var
opp_string wsmData_var
int senderAddress_var
int recipientAddress_var
int serial_var
Coord senderPos_var
simtime_t timestamp_var
Private Member Functions
void copy (const WaveShortMessage &other)
Detailed Description
Class generated from veins/modules/messages/WaveShortMessage.msg:27 by nedtool.
packet WaveShortMessage
{
    //Version of the Wave Short Message
    int wsmVersion = 0;
    //Determine which security mechanism was used
    int securityType = 0;
    //Channel Number on which this packet was sent
    int channelNumber;
    //Data rate with which this packet was sent
    int dataRate = 1;
    //Power Level with which this packet was sent
    int priority = 3;
    //Unique number to identify the service
    int psid = 0;
    //Provider Service Context
    string psc = "Service with some Data";
    //Length of Wave Short Message
    int wsmLength;
    //Data of Wave Short Message
    string wsmData = "Some Data";
    int senderAddress = 0;
    int recipientAddress = -1;
    int serial = 0;
    Coord senderPos;
    simtime_t timestamp = 0;
}
Definition at line 54 of file WaveShortMessage_m.h.
Constructor & Destructor Documentation
WaveShortMessage::WaveShortMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
WaveShortMessage::WaveShortMessage (const WaveShortMessage & other)
virtual WaveShortMessage::~WaveShortMessage () virtual
Member Function Documentation
void WaveShortMessage::copy (const WaveShortMessage & other) private
virtual WaveShortMessage* WaveShortMessage::dup () const inline virtual
Definition at line 84 of file WaveShortMessage_m.h.
Referenced by Mac1609_4::handleSelfMsg().
 {return new WaveShortMessage(*this);}
virtual int WaveShortMessage::getChannelNumber () const virtual
Referenced by Mac1609_4::handleUpperMsg().
virtual int WaveShortMessage::getDataRate () const virtual
virtual int WaveShortMessage::getPriority () const virtual
Referenced by Mac1609_4::handleSelfMsg(), and Mac1609_4::handleUpperMsg().
virtual const char* WaveShortMessage::getPsc () const virtual
virtual int WaveShortMessage::getPsid () const virtual
virtual int WaveShortMessage::getRecipientAddress () const virtual
virtual int WaveShortMessage::getSecurityType () const virtual
virtual int WaveShortMessage::getSenderAddress () const virtual
virtual Coord& WaveShortMessage::getSenderPos () virtual
Referenced by TraCIDemoRSU11p::onData(), and TraCIDemo11p::onData().
virtual const Coord& WaveShortMessage::getSenderPos () const inline virtual
Definition at line 114 of file WaveShortMessage_m.h.
Referenced by getSenderPos().
 {return const_cast<WaveShortMessage*>(this)->getSenderPos();}
virtual int WaveShortMessage::getSerial () const virtual
virtual simtime_t WaveShortMessage::getTimestamp () const virtual
Referenced by BaseWaveApplLayer::prepareWSM().
virtual const char* WaveShortMessage::getWsmData () const virtual
Referenced by TraCIDemoRSU11p::onData(), and TraCIDemo11p::onData().
virtual int WaveShortMessage::getWsmLength () const virtual
virtual int WaveShortMessage::getWsmVersion () const virtual
WaveShortMessage& WaveShortMessage::operator= (const WaveShortMessage & other)
bool WaveShortMessage::operator== (const WaveShortMessage &) protected
virtual void WaveShortMessage::parsimPack (cCommBuffer * b) virtual
Referenced by doPacking().
virtual void WaveShortMessage::parsimUnpack (cCommBuffer * b) virtual
Referenced by doUnpacking().
virtual void WaveShortMessage::setChannelNumber (int channelNumber) virtual
Referenced by Mac1609_4::handleUpperMsg(), and BaseWaveApplLayer::prepareWSM().
virtual void WaveShortMessage::setDataRate (int dataRate) virtual
virtual void WaveShortMessage::setPriority (int priority) virtual
Referenced by BaseWaveApplLayer::prepareWSM().
virtual void WaveShortMessage::setPsc (const char * psc) virtual
virtual void WaveShortMessage::setPsid (int psid) virtual
Referenced by BaseWaveApplLayer::prepareWSM().
virtual void WaveShortMessage::setRecipientAddress (int recipientAddress) virtual
Referenced by BaseWaveApplLayer::prepareWSM().
virtual void WaveShortMessage::setSecurityType (int securityType) virtual
virtual void WaveShortMessage::setSenderAddress (int senderAddress) virtual
Referenced by BaseWaveApplLayer::prepareWSM().
virtual void WaveShortMessage::setSenderPos (const Coord & senderPos) virtual
Referenced by BaseWaveApplLayer::prepareWSM().
virtual void WaveShortMessage::setSerial (int serial) virtual
Referenced by BaseWaveApplLayer::prepareWSM().
virtual void WaveShortMessage::setTimestamp (simtime_t timestamp) virtual
Referenced by BaseWaveApplLayer::prepareWSM().
virtual void WaveShortMessage::setWsmData (const char * wsmData) virtual
Referenced by TraCIDemoRSU11p::sendMessage(), and TraCIDemo11p::sendMessage().
virtual void WaveShortMessage::setWsmLength (int wsmLength) virtual
virtual void WaveShortMessage::setWsmVersion (int wsmVersion) virtual
Referenced by BaseWaveApplLayer::prepareWSM().
Member Data Documentation
int WaveShortMessage::channelNumber_var protected
Definition at line 59 of file WaveShortMessage_m.h.
int WaveShortMessage::dataRate_var protected
Definition at line 60 of file WaveShortMessage_m.h.
int WaveShortMessage::priority_var protected
Definition at line 61 of file WaveShortMessage_m.h.
opp_string WaveShortMessage::psc_var protected
Definition at line 63 of file WaveShortMessage_m.h.
int WaveShortMessage::psid_var protected
Definition at line 62 of file WaveShortMessage_m.h.
int WaveShortMessage::recipientAddress_var protected
Definition at line 67 of file WaveShortMessage_m.h.
int WaveShortMessage::securityType_var protected
Definition at line 58 of file WaveShortMessage_m.h.
int WaveShortMessage::senderAddress_var protected
Definition at line 66 of file WaveShortMessage_m.h.
Coord WaveShortMessage::senderPos_var protected
Definition at line 69 of file WaveShortMessage_m.h.
int WaveShortMessage::serial_var protected
Definition at line 68 of file WaveShortMessage_m.h.
simtime_t WaveShortMessage::timestamp_var protected
Definition at line 70 of file WaveShortMessage_m.h.
opp_string WaveShortMessage::wsmData_var protected
Definition at line 65 of file WaveShortMessage_m.h.
int WaveShortMessage::wsmLength_var protected
Definition at line 64 of file WaveShortMessage_m.h.
int WaveShortMessage::wsmVersion_var protected
Definition at line 57 of file WaveShortMessage_m.h.
The documentation for this class was generated from the following file:
WaveShortMessage_m.h