Veins Framework: BaseConnectionManager::CoordSet Class Reference
BaseConnectionManager::CoordSet Class Reference
Represents an minimalistic (hash)set of GridCoords.
Public Member Functions
CoordSet (unsigned sz)
Initializes the set (hashtable) with the a specified size.
~CoordSet ()
Delete every created GridCoord.
void add (const GridCoord &c)
Adds a GridCoord to the set.
GridCoord * next ()
Returns the next GridCoord in the set.
unsigned getSize ()
Returns the number of GridCoords currently saved in this set.
unsigned getmaxSize ()
Returns the maximum number of elements which can be stored inside this set.
Protected Member Functions
void insert (const GridCoord &c, unsigned pos)
Tries to insert a GridCoord at the specified position.
Protected Attributes
std::vector< GridCoord * > data
Holds the hash table.
unsigned maxSize
maximum size of the hash table.
unsigned size
Current number of entries in the hash table.
unsigned current
Holds the current element when iterating over this table.
Detailed Description
Represents an minimalistic (hash)set of GridCoords.
It is a workaround because c++ doesn't come with an hash set.
Definition at line 110 of file BaseConnectionManager.h.
Constructor & Destructor Documentation
BaseConnectionManager::CoordSet::CoordSet (unsigned sz) inline
Initializes the set (hashtable) with the a specified size.
Definition at line 146 of file BaseConnectionManager.h.
                         :maxSize(sz), size(0), current(0)
                 {
                         data.resize(maxSize);
                 }
BaseConnectionManager::CoordSet::~CoordSet () inline
Delete every created GridCoord.
Definition at line 155 of file BaseConnectionManager.h.
{
                         for(unsigned i = 0; i < maxSize; i++) {
                                 if(data[i] != 0) {
                                         delete data[i];
                                 }
                         }
                 }
Member Function Documentation
void BaseConnectionManager::CoordSet::add (const GridCoord & c) inline
Adds a GridCoord to the set.
If a GridCoord with the same value already exists in the set nothing happens.
Definition at line 168 of file BaseConnectionManager.h.
Referenced by BaseConnectionManager::checkGrid(), BaseConnectionManager::fillUnionWithNeighbors(), and BaseConnectionManager::unregisterNic().
{
                         unsigned hash = (c.x * 10000 + c.y * 100 + c.z) % maxSize;
                         insert(c, hash);
                 }
unsigned BaseConnectionManager::CoordSet::getmaxSize () inline
Returns the maximum number of elements which can be stored inside this set.
To prevent collisions the set should never be more than 75% filled.
Definition at line 196 of file BaseConnectionManager.h.
 { return maxSize; }
unsigned BaseConnectionManager::CoordSet::getSize () inline
Returns the number of GridCoords currently saved in this set.
Definition at line 189 of file BaseConnectionManager.h.
 { return size; }
void BaseConnectionManager::CoordSet::insert (const GridCoord & c, unsigned pos) inline protected
Tries to insert a GridCoord at the specified position.
If the same Coord already exists there nothing happens. If an other Coord already exists there calculate a new Position to insert end recursively call this Method again. If the spot is empty the Coord is inserted.
Definition at line 131 of file BaseConnectionManager.h.
{
                         if(data[pos] == 0) {
                                 data[pos] = new GridCoord(c);
                                 size++;
                         } else {
                                 if(*data[pos] != c) {
                                         insert(c, (pos + 2) % maxSize);
                                 }
                         }
                 }
GridCoord* BaseConnectionManager::CoordSet::next () inline
Returns the next GridCoord in the set.
You can iterate through the set only one time with this function!
Definition at line 177 of file BaseConnectionManager.h.
Referenced by BaseConnectionManager::checkGrid(), and BaseConnectionManager::unregisterNic().
{
                         for(;current < maxSize; current++) {
                                 if(data[current] != 0) {
                                         return data[current++];
                                 }
                         }
                         return 0;
                 }
Member Data Documentation
unsigned BaseConnectionManager::CoordSet::current protected
Holds the current element when iterating over this table.
Definition at line 119 of file BaseConnectionManager.h.
std::vector<GridCoord*> BaseConnectionManager::CoordSet::data protected
Holds the hash table.
Definition at line 113 of file BaseConnectionManager.h.
unsigned BaseConnectionManager::CoordSet::maxSize protected
maximum size of the hash table.
Definition at line 115 of file BaseConnectionManager.h.
unsigned BaseConnectionManager::CoordSet::size protected
Current number of entries in the hash table.
Definition at line 117 of file BaseConnectionManager.h.
The documentation for this class was generated from the following file:
BaseConnectionManager.h