Veins Framework: PhyControlMessage Class Reference
PhyControlMessage Class Reference
Class generated from veins/modules/messages/PhyControlMessage.msg:22 by nedtool.
#include <PhyControlMessage_m.h>
Public Member Functions
PhyControlMessage (const char *name=NULL, int kind=0)
PhyControlMessage (const PhyControlMessage &other)
virtual ~PhyControlMessage ()
PhyControlMessage & operator= (const PhyControlMessage &other)
virtual PhyControlMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getMcs () const
virtual void setMcs (int mcs)
virtual double getTxPower_mW () const
virtual void setTxPower_mW (double txPower_mW)
Protected Member Functions
bool operator== (const PhyControlMessage &)
Protected Attributes
int mcs_var
double txPower_mW_var
Private Member Functions
void copy (const PhyControlMessage &other)
Detailed Description
Class generated from veins/modules/messages/PhyControlMessage.msg:22 by nedtool.
//
// Defines a control message that can be associated with a MAC frame to set
// transmission power and datarate on a per packet basis
//
message PhyControlMessage
{
    //modulation and coding scheme to be used (see enum TxMCS in ConstsPhy.h)
    int mcs;
    //transmission power to be used in mW
    double txPower_mW;
}
Definition at line 34 of file PhyControlMessage_m.h.
Constructor & Destructor Documentation
PhyControlMessage::PhyControlMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
PhyControlMessage::PhyControlMessage (const PhyControlMessage & other)
virtual PhyControlMessage::~PhyControlMessage () virtual
Member Function Documentation
void PhyControlMessage::copy (const PhyControlMessage & other) private
virtual PhyControlMessage* PhyControlMessage::dup () const inline virtual
Definition at line 52 of file PhyControlMessage_m.h.
 {return new PhyControlMessage(*this);}
virtual int PhyControlMessage::getMcs () const virtual
Referenced by Mac1609_4::handleSelfMsg().
virtual double PhyControlMessage::getTxPower_mW () const virtual
Referenced by Mac1609_4::handleSelfMsg().
PhyControlMessage& PhyControlMessage::operator= (const PhyControlMessage & other)
bool PhyControlMessage::operator== (const PhyControlMessage &) protected
virtual void PhyControlMessage::parsimPack (cCommBuffer * b) virtual
Referenced by doPacking().
virtual void PhyControlMessage::parsimUnpack (cCommBuffer * b) virtual
Referenced by doUnpacking().
virtual void PhyControlMessage::setMcs (int mcs) virtual
virtual void PhyControlMessage::setTxPower_mW (double txPower_mW) virtual
Member Data Documentation
int PhyControlMessage::mcs_var protected
Definition at line 37 of file PhyControlMessage_m.h.
double PhyControlMessage::txPower_mW_var protected
Definition at line 38 of file PhyControlMessage_m.h.
The documentation for this class was generated from the following file:
PhyControlMessage_m.h