Veins Framework: BorderMsg Class Reference
BorderMsg Class Reference
Class generated from veins/base/messages/BorderMsg.msg:34 by nedtool.
#include <BorderMsg_m.h>
Public Member Functions
BorderMsg (const char *name=NULL, int kind=0)
BorderMsg (const BorderMsg &other)
virtual ~BorderMsg ()
BorderMsg & operator= (const BorderMsg &other)
virtual BorderMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getPolicy () const
virtual void setPolicy (int policy)
virtual Coord & getStartPos ()
virtual const Coord & getStartPos () const
virtual void setStartPos (const Coord &startPos)
virtual Coord & getDirection ()
virtual const Coord & getDirection () const
virtual void setDirection (const Coord &direction)
Protected Member Functions
bool operator== (const BorderMsg &)
Protected Attributes
int policy_var
Coord startPos_var
Coord direction_var
Private Member Functions
void copy (const BorderMsg &other)
Detailed Description
Class generated from veins/base/messages/BorderMsg.msg:34 by nedtool.
// used as a self packet containing the position, direction and BorderPolicy
//
//
Author
 Daniel Willkomm
//
packet BorderMsg
{
    int policy;    // border policy to use for the host
    Coord startPos; // new start position of the host
    Coord direction; // new direction of the host
}
Definition at line 37 of file BorderMsg_m.h.
Constructor & Destructor Documentation
BorderMsg::BorderMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
BorderMsg::BorderMsg (const BorderMsg & other)
virtual BorderMsg::~BorderMsg () virtual
Member Function Documentation
void BorderMsg::copy (const BorderMsg & other) private
virtual BorderMsg* BorderMsg::dup () const inline virtual
Definition at line 56 of file BorderMsg_m.h.
 {return new BorderMsg(*this);}
virtual Coord& BorderMsg::getDirection () virtual
Referenced by BaseMobility::handleBorderMsg().
virtual const Coord& BorderMsg::getDirection () const inline virtual
Definition at line 67 of file BorderMsg_m.h.
Referenced by getDirection().
 {return const_cast<BorderMsg*>(this)->getDirection();}
virtual int BorderMsg::getPolicy () const virtual
Referenced by BaseMobility::handleBorderMsg().
virtual Coord& BorderMsg::getStartPos () virtual
Referenced by BaseMobility::handleBorderMsg().
virtual const Coord& BorderMsg::getStartPos () const inline virtual
Definition at line 64 of file BorderMsg_m.h.
Referenced by getStartPos().
 {return const_cast<BorderMsg*>(this)->getStartPos();}
BorderMsg& BorderMsg::operator= (const BorderMsg & other)
bool BorderMsg::operator== (const BorderMsg &) protected
virtual void BorderMsg::parsimPack (cCommBuffer * b) virtual
Referenced by doPacking().
virtual void BorderMsg::parsimUnpack (cCommBuffer * b) virtual
Referenced by doUnpacking().
virtual void BorderMsg::setDirection (const Coord & direction) virtual
Referenced by BaseMobility::handleIfOutside().
virtual void BorderMsg::setPolicy (int policy) virtual
Referenced by BaseMobility::handleIfOutside().
virtual void BorderMsg::setStartPos (const Coord & startPos) virtual
Referenced by BaseMobility::handleIfOutside().
Member Data Documentation
Coord BorderMsg::direction_var protected
Definition at line 42 of file BorderMsg_m.h.
int BorderMsg::policy_var protected
Definition at line 40 of file BorderMsg_m.h.
Coord BorderMsg::startPos_var protected
Definition at line 41 of file BorderMsg_m.h.
The documentation for this class was generated from the following file:
BorderMsg_m.h