SUMO - Simulation of Urban MObility: DijkstraRouterEffortBase< E, V, PF > Class Template Reference
DijkstraRouterEffortBase< E, V, PF > Class Template Reference abstract
#include <DijkstraRouterEffort.h>
Data Structures
struct EdgeInfo
class EdgeInfoByEffortComparator
Public Member Functions
void buildPathFrom (EdgeInfo *rbegin, std::vector< const E * > &edges)
Builds the path from marked edges.
virtual void compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > &into)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
DijkstraRouterEffortBase (size_t noE, bool unbuildIsWarning)
Constructor.
void endQuery (int visits)
virtual SUMOReal getEffort (const E *const e, const V *const v, SUMOReal t) const =0
virtual SUMOReal getTravelTime (const E *const e, const V *const v, SUMOReal t) const =0
void init ()
virtual void prepare (const E *, const V *, bool)
SUMOReal recomputeCosts (const std::vector< const E * > &edges, const V *const v, SUMOTime msTime) const
void startQuery ()
virtual ~DijkstraRouterEffortBase ()
Destructor.
Protected Attributes
EdgeInfoByEffortComparator myComparator
std::vector< EdgeInfo > myEdgeInfos
The container of edge information.
MsgHandler *const myErrorMsgHandler
the handler for routing errors
std::vector< EdgeInfo * > myFound
list of visited Edges (for resetting)
std::vector< EdgeInfo * > myFrontierList
A container for reusage of the min edge heap.
Detailed Description
template<class E, class V, class PF>
class DijkstraRouterEffortBase< E, V, PF >
Definition at line 67 of file DijkstraRouterEffort.h.
Constructor & Destructor Documentation
template<class E, class V, class PF> DijkstraRouterEffortBase< E, V, PF >::DijkstraRouterEffortBase (size_t noE, bool unbuildIsWarning) inline
Constructor.
Definition at line 73 of file DijkstraRouterEffort.h.
template<class E, class V, class PF> virtual DijkstraRouterEffortBase< E, V, PF >::~DijkstraRouterEffortBase () inline virtual
Destructor.
Definition at line 82 of file DijkstraRouterEffort.h.
Member Function Documentation
template<class E, class V, class PF> void DijkstraRouterEffortBase< E, V, PF >::buildPathFrom (EdgeInfo * rbegin, std::vector< const E * > & edges) inline
Builds the path from marked edges.
Definition at line 226 of file DijkstraRouterEffort.h.
Referenced by DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> virtual void DijkstraRouterEffortBase< E, V, PF >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > & into) inline virtual
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Implements SUMOAbstractRouter< E, V >.
Definition at line 150 of file DijkstraRouterEffort.h.
template<class E, class V> void SUMOAbstractRouter< E, V >::endQuery (int visits) inline inherited
Definition at line 90 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> virtual SUMOReal DijkstraRouterEffortBase< E, V, PF >::getEffort (const E *const e, const V *const v, SUMOReal t) const pure virtual
Implemented in DijkstraRouterEffort_Direct< E, V, PF >, DijkstraRouterEffort_ByProxi< E, V, PF >, and DijkstraRouterEffort_ByProxi< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >.
Referenced by DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::recomputeCosts().
template<class E, class V, class PF> virtual SUMOReal DijkstraRouterEffortBase< E, V, PF >::getTravelTime (const E *const e, const V *const v, SUMOReal t) const pure virtual
Implemented in DijkstraRouterEffort_Direct< E, V, PF >, DijkstraRouterEffort_ByProxi< E, V, PF >, and DijkstraRouterEffort_ByProxi< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >.
Referenced by DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::recomputeCosts().
template<class E, class V, class PF> void DijkstraRouterEffortBase< E, V, PF >::init () inline
Definition at line 135 of file DijkstraRouterEffort.h.
Referenced by DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V> virtual void SUMOAbstractRouter< E, V >::prepare (const E * , const V * , bool) inline virtual inherited
Definition at line 81 of file SUMOAbstractRouter.h.
template<class E, class V, class PF> SUMOReal DijkstraRouterEffortBase< E, V, PF >::recomputeCosts (const std::vector< const E * > & edges, const V *const v, SUMOTime msTime) const inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 211 of file DijkstraRouterEffort.h.
template<class E, class V> void SUMOAbstractRouter< E, V >::startQuery () inline inherited
Definition at line 85 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
Field Documentation
template<class E, class V, class PF> EdgeInfoByEffortComparator DijkstraRouterEffortBase< E, V, PF >::myComparator protected
Definition at line 244 of file DijkstraRouterEffort.h.
Referenced by DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> std::vector<EdgeInfo> DijkstraRouterEffortBase< E, V, PF >::myEdgeInfos protected
The container of edge information.
Definition at line 237 of file DijkstraRouterEffort.h.
Referenced by DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::DijkstraRouterEffortBase().
template<class E, class V, class PF> MsgHandler* const DijkstraRouterEffortBase< E, V, PF >::myErrorMsgHandler protected
the handler for routing errors
Definition at line 247 of file DijkstraRouterEffort.h.
Referenced by DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> std::vector<EdgeInfo*> DijkstraRouterEffortBase< E, V, PF >::myFound protected
list of visited Edges (for resetting)
Definition at line 242 of file DijkstraRouterEffort.h.
Referenced by DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::init().
template<class E, class V, class PF> std::vector<EdgeInfo*> DijkstraRouterEffortBase< E, V, PF >::myFrontierList protected
A container for reusage of the min edge heap.
Definition at line 240 of file DijkstraRouterEffort.h.
Referenced by DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::init().
The documentation for this class was generated from the following file:
DijkstraRouterEffort.h