SUMO - Simulation of Urban MObility: GUIColorer Class Reference
GUIColorer Class Reference
Base class for coloring. Allows changing the used colors and sets the used color in dependence to a value.
#include <GUIColorer.h>
Public Member Functions
void addScheme (GUIColorScheme scheme)
void fill (FXComboBox &cb)
Fills the given combobox with the names of available colorings.
size_t getActive () const
GUIColorScheme & getScheme ()
const GUIColorScheme & getScheme () const
GUIColorScheme * getSchemeByName (std::string name)
GUIColorer ()
Constructor.
bool operator== (const GUIColorer &c) const
void save (OutputDevice &dev) const
void setActive (size_t scheme)
virtual ~GUIColorer ()
Destructor.
Protected Attributes
size_t myActiveScheme
std::vector< GUIColorScheme > mySchemes
Detailed Description
Base class for coloring. Allows changing the used colors and sets the used color in dependence to a value.
Definition at line 50 of file GUIColorer.h.
Constructor & Destructor Documentation
GUIColorer::GUIColorer () inline
Constructor.
Definition at line 53 of file GUIColorer.h.
virtual GUIColorer::~GUIColorer () inline virtual
Destructor.
Definition at line 56 of file GUIColorer.h.
Member Function Documentation
void GUIColorer::addScheme (GUIColorScheme scheme) inline
Definition at line 104 of file GUIColorer.h.
References mySchemes.
Referenced by GUIVisualizationSettings::GUIVisualizationSettings().
void GUIColorer::fill (FXComboBox & cb) inline
Fills the given combobox with the names of available colorings.
Definition at line 59 of file GUIColorer.h.
References myActiveScheme, and mySchemes.
size_t GUIColorer::getActive () const inline
Definition at line 72 of file GUIColorer.h.
References myActiveScheme.
Referenced by GUIJunctionWrapper::drawGL(), GUIVisualizationSettings::getLaneEdgeMode(), GUIDialog_ViewSettings::onCmdColorChange(), GUIDialog_ViewSettings::onCmdNameChange(), GUIVisualizationSettings::save(), GUIPerson::setColor(), GUILane::setColor(), and GUIVehicle::setColor().
GUIColorScheme& GUIColorer::getScheme () inline
Definition at line 76 of file GUIColorer.h.
References myActiveScheme, and mySchemes.
Referenced by GUIJunctionWrapper::drawGL(), GUIVisualizationSettings::getLaneEdgeScheme(), GUIDialog_ViewSettings::onCmdColorChange(), GUIDialog_ViewSettings::rebuildColorMatrices(), GUIPerson::setColor(), GUILane::setColor(), and GUIVehicle::setColor().
const GUIColorScheme& GUIColorer::getScheme () const inline
Definition at line 80 of file GUIColorer.h.
References myActiveScheme, and mySchemes.
GUIColorScheme* GUIColorer::getSchemeByName (std::string name) inline
Definition at line 84 of file GUIColorer.h.
References mySchemes.
Referenced by GUISettingsHandler::myStartElement().
bool GUIColorer::operator== (const GUIColorer & c) const inline
Definition at line 99 of file GUIColorer.h.
References myActiveScheme, and mySchemes.
void GUIColorer::save (OutputDevice & dev) const inline
Definition at line 93 of file GUIColorer.h.
References mySchemes.
Referenced by GUIVisualizationSettings::save().
void GUIColorer::setActive (size_t scheme) inline
Definition at line 66 of file GUIColorer.h.
References myActiveScheme, and mySchemes.
Referenced by GUISettingsHandler::myStartElement(), GUIDialog_ViewSettings::onCmdColorChange(), and GUIApplicationWindow::onCmdEditChosen().
Field Documentation
size_t GUIColorer::myActiveScheme protected
Definition at line 110 of file GUIColorer.h.
Referenced by fill(), getActive(), getScheme(), operator==(), and setActive().
std::vector<GUIColorScheme> GUIColorer::mySchemes protected
Definition at line 111 of file GUIColorer.h.
Referenced by addScheme(), fill(), getScheme(), getSchemeByName(), operator==(), save(), and setActive().
The documentation for this class was generated from the following file:
GUIColorer.h