SUMO - Simulation of Urban MObility: NWWriter_XML Class Reference
NWWriter_XML Class Reference
Exporter writing networks using XML (native input) format.
#include <NWWriter_XML.h>
Static Public Member Functions
static void writeJoinedJunctions (const OptionsCont &oc, NBNodeCont &nc)
Writes the joined-juncionts to file.
static void writeNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Writes the network into XML-files (nodes, edges, connections, traffic lights)
static void writeStreetSigns (const OptionsCont &oc, NBEdgeCont &ec)
Writes street signs as POIs to file.
Static Private Member Functions
static void writeEdgesAndConnections (const OptionsCont &oc, NBNodeCont &nc, NBEdgeCont &ec)
Writes the edges and connections files.
static void writeNodes (const OptionsCont &oc, NBNodeCont &nc)
Writes the nodes file.
static void writeTrafficLights (const OptionsCont &oc, NBTrafficLightLogicCont &tc, NBEdgeCont &ec)
Writes the traffic lights file.
Detailed Description
Exporter writing networks using XML (native input) format.
Definition at line 62 of file NWWriter_XML.h.
Member Function Documentation
void NWWriter_XML::writeEdgesAndConnections (const OptionsCont & oc, NBNodeCont & nc, NBEdgeCont & ec) static private
Writes the edges and connections files.
Parameters
[in] oc The options to use
[in] nc The node-container from which to read data
[in] ec The edge-container from which to read data
Definition at line 144 of file NWWriter_XML.cpp.
References NBNodeCont::begin(), NBEdgeCont::begin(), GeoConvHelper::cartesian2geo(), OutputDevice::close(), OutputDevice::closeTag(), NBNode::DEFAULT_CROSSING_WIDTH, NBNodeCont::end(), NBEdgeCont::end(), NBEdge::Lane::endOffset, StringUtils::escapeXML(), OptionsCont::exists(), GEO_OUTPUT_ACCURACY, OptionsCont::getBool(), NBEdge::getConnections(), OutputDevice::getDevice(), NBEdge::getEndOffset(), GeoConvHelper::getFinal(), NBEdge::getFromNode(), NBEdge::getGeometry(), Named::getID(), NBEdge::getLanes(), NBEdge::getLaneSpreadFunction(), NBEdge::getLaneWidth(), NBEdge::getLoadedLength(), NBEdge::getNumLanes(), NBEdge::getPriority(), NBEdge::getSpeed(), NBEdge::getStreetName(), OptionsCont::getString(), NBEdge::getToNode(), NBEdge::getTypeID(), NBEdge::hasDefaultGeometry(), NBEdge::hasLaneSpecificEndOffset(), NBEdge::hasLaneSpecificSpeed(), NBEdge::hasLaneSpecificWidth(), NBEdge::hasLoadedLength(), LANESPREAD_RIGHT, NWFrame::MAJOR_VERSION, NBEdge::needsLaneSpecificOutput(), OutputDevice::openTag(), NBEdge::Lane::permissions, NWWriter_SUMO::PLAIN, NBEdge::Lane::preferred, OutputDevice::setPrecision(), NBEdge::sortOutgoingConnectionsByIndex(), NBEdge::Lane::speed, SUMO_ATTR_EDGES, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_LENGTH, SUMO_ATTR_NAME, SUMO_ATTR_NODE, SUMO_ATTR_NUMLANES, SUMO_ATTR_PRIORITY, SUMO_ATTR_SHAPE, SUMO_ATTR_SPEED, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_TO, SUMO_ATTR_TYPE, SUMO_ATTR_WIDTH, SUMO_TAG_CROSSING, SUMO_TAG_EDGE, SUMO_TAG_LANE, toString(), NBEdge::UNSPECIFIED_OFFSET, NBEdge::UNSPECIFIED_WIDTH, GeoConvHelper::usingInverseGeoProjection(), NBEdge::Lane::width, OutputDevice::writeAttr(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writePermissions(), NWWriter_SUMO::writePreferences(), NWWriter_SUMO::writeProhibitions(), and OutputDevice::writeXMLHeader().
Referenced by writeNetwork().
void NWWriter_XML::writeJoinedJunctions (const OptionsCont & oc, NBNodeCont & nc) static
Writes the joined-juncionts to file.
Parameters
[in] oc The options to use
[in] nc The node-container from which to read data
Definition at line 284 of file NWWriter_XML.cpp.
References OutputDevice::close(), OutputDevice::closeTag(), OutputDevice::getDevice(), NBNodeCont::getJoinedClusters(), OptionsCont::getString(), NWFrame::MAJOR_VERSION, OutputDevice::openTag(), SUMO_ATTR_NODES, SUMO_TAG_JOIN, OutputDevice::writeAttr(), and OutputDevice::writeXMLHeader().
Referenced by writeNetwork().
void NWWriter_XML::writeNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Writes the network into XML-files (nodes, edges, connections, traffic lights)
Parameters
[in] oc The options to use
[in] nb The network builder from which to read data
Definition at line 61 of file NWWriter_XML.cpp.
References NBNetBuilder::getEdgeCont(), NBNetBuilder::getNodeCont(), NBNetBuilder::getTLLogicCont(), OptionsCont::isSet(), writeEdgesAndConnections(), writeJoinedJunctions(), writeNodes(), writeStreetSigns(), and writeTrafficLights().
Referenced by NWFrame::writeNetwork().
void NWWriter_XML::writeNodes (const OptionsCont & oc, NBNodeCont & nc) static private
Writes the nodes file.
Parameters
[in] oc The options to use
[in] nc The node-container from which to read data
Definition at line 78 of file NWWriter_XML.cpp.
References NBNodeCont::begin(), GeoConvHelper::cartesian2geo(), OutputDevice::close(), OutputDevice::closeTag(), NBNodeCont::end(), OptionsCont::exists(), GEO_OUTPUT_ACCURACY, OptionsCont::getBool(), NBNode::getControllingTLS(), OutputDevice::getDevice(), GeoConvHelper::getFinal(), Named::getID(), NBNode::getPosition(), NBNode::getShape(), OptionsCont::getString(), NBNode::getType(), NBNode::hasCustomShape(), NBNode::isTLControlled(), joinToString(), NWFrame::MAJOR_VERSION, OutputDevice::openTag(), OutputDevice::setPrecision(), SUMO_ATTR_CONTROLLED_INNER, SUMO_ATTR_ID, SUMO_ATTR_SHAPE, SUMO_ATTR_TLID, SUMO_ATTR_TYPE, SUMO_TAG_NODE, toString(), GeoConvHelper::usingGeoProjection(), GeoConvHelper::usingInverseGeoProjection(), WRITE_WARNING, OutputDevice::writeAttr(), NWWriter_SUMO::writeLocation(), NWFrame::writePositionLong(), and OutputDevice::writeXMLHeader().
Referenced by writeNetwork().
void NWWriter_XML::writeStreetSigns (const OptionsCont & oc, NBEdgeCont & ec) static
Writes street signs as POIs to file.
Parameters
[in] oc The options to use
[in] ec The edge-container from which to read data
Definition at line 306 of file NWWriter_XML.cpp.
References NBEdgeCont::begin(), OutputDevice::close(), NBEdgeCont::end(), OutputDevice::getDevice(), NBEdge::getSigns(), OptionsCont::getString(), NWFrame::MAJOR_VERSION, and OutputDevice::writeXMLHeader().
Referenced by writeNetwork().
void NWWriter_XML::writeTrafficLights (const OptionsCont & oc, NBTrafficLightLogicCont & tc, NBEdgeCont & ec) static private
Writes the traffic lights file.
Parameters
[in] oc The options to use
[in] tc The tll-container from which to read data
[in] ec The edge-container from which to read data
Definition at line 263 of file NWWriter_XML.cpp.
References NBEdgeCont::begin(), OutputDevice::close(), NBEdgeCont::end(), NBEdge::getConnections(), OutputDevice::getDevice(), OptionsCont::getString(), NWFrame::MAJOR_VERSION, NWWriter_SUMO::TLL, NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeTrafficLights(), and OutputDevice::writeXMLHeader().
Referenced by writeNetwork().
The documentation for this class was generated from the following files:
NWWriter_XML.h
NWWriter_XML.cpp