SUMO - Simulation of Urban MObility: AStarRouterTTBase< E, V, PF > Class Template Reference
AStarRouterTTBase< E, V, PF > Class Template Reference abstract
#include <AStarRouter.h>
Data Structures
struct EdgeInfo
class EdgeInfoComparator
Public Member Functions
AStarRouterTTBase (size_t noE, bool unbuildIsWarning)
Constructor.
void buildPathFrom (EdgeInfo *rbegin, std::vector< const E * > &edges)
Builds the path from marked edges.
virtual void compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > &into)
Builds the route between the given edges using the minimum travel time.
void endQuery (int visits)
virtual SUMOReal getEffort (const E *const e, const V *const v, SUMOReal t) const =0
void init ()
virtual void prepare (const E *, const V *, bool)
SUMOReal recomputeCosts (const std::vector< const E * > &edges, const V *const v, SUMOTime msTime) const
void startQuery ()
virtual ~AStarRouterTTBase ()
Destructor.
Protected Attributes
EdgeInfoComparator myComparator
std::vector< EdgeInfo > myEdgeInfos
The container of edge information.
MsgHandler *const myErrorMsgHandler
the handler for routing errors
std::vector< EdgeInfo * > myFound
list of visited Edges (for resetting)
std::vector< EdgeInfo * > myFrontierList
A container for reusage of the min edge heap.
Detailed Description
template<class E, class V, class PF>
class AStarRouterTTBase< E, V, PF >
Definition at line 69 of file AStarRouter.h.
Constructor & Destructor Documentation
template<class E, class V, class PF> AStarRouterTTBase< E, V, PF >::AStarRouterTTBase (size_t noE, bool unbuildIsWarning) inline
Constructor.
Definition at line 75 of file AStarRouter.h.
template<class E, class V, class PF> virtual AStarRouterTTBase< E, V, PF >::~AStarRouterTTBase () inline virtual
Destructor.
Definition at line 84 of file AStarRouter.h.
Member Function Documentation
template<class E, class V, class PF> void AStarRouterTTBase< E, V, PF >::buildPathFrom (EdgeInfo * rbegin, std::vector< const E * > & edges) inline
Builds the path from marked edges.
Definition at line 235 of file AStarRouter.h.
Referenced by AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> virtual void AStarRouterTTBase< E, V, PF >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > & into) inline virtual
Builds the route between the given edges using the minimum travel time.
Implements SUMOAbstractRouter< E, V >.
Definition at line 157 of file AStarRouter.h.
template<class E, class V> void SUMOAbstractRouter< E, V >::endQuery (int visits) inline inherited
Definition at line 90 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> virtual SUMOReal AStarRouterTTBase< E, V, PF >::getEffort (const E *const e, const V *const v, SUMOReal t) const pure virtual
Implemented in AStarRouterTT_Direct< E, V, PF >, AStarRouterTT_ByProxi< E, V, PF >, and AStarRouterTT_ByProxi< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >.
Referenced by AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::recomputeCosts().
template<class E, class V, class PF> void AStarRouterTTBase< E, V, PF >::init () inline
Definition at line 143 of file AStarRouter.h.
Referenced by AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V> virtual void SUMOAbstractRouter< E, V >::prepare (const E * , const V * , bool) inline virtual inherited
Definition at line 81 of file SUMOAbstractRouter.h.
template<class E, class V, class PF> SUMOReal AStarRouterTTBase< E, V, PF >::recomputeCosts (const std::vector< const E * > & edges, const V *const v, SUMOTime msTime) const inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 221 of file AStarRouter.h.
template<class E, class V> void SUMOAbstractRouter< E, V >::startQuery () inline inherited
Definition at line 85 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
Field Documentation
template<class E, class V, class PF> EdgeInfoComparator AStarRouterTTBase< E, V, PF >::myComparator protected
Definition at line 253 of file AStarRouter.h.
Referenced by AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> std::vector<EdgeInfo> AStarRouterTTBase< E, V, PF >::myEdgeInfos protected
The container of edge information.
Definition at line 246 of file AStarRouter.h.
Referenced by AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::AStarRouterTTBase(), and AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> MsgHandler* const AStarRouterTTBase< E, V, PF >::myErrorMsgHandler protected
the handler for routing errors
Definition at line 256 of file AStarRouter.h.
Referenced by AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> std::vector<EdgeInfo*> AStarRouterTTBase< E, V, PF >::myFound protected
list of visited Edges (for resetting)
Definition at line 251 of file AStarRouter.h.
Referenced by AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::init().
template<class E, class V, class PF> std::vector<EdgeInfo*> AStarRouterTTBase< E, V, PF >::myFrontierList protected
A container for reusage of the min edge heap.
Definition at line 249 of file AStarRouter.h.
Referenced by AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::init().
The documentation for this class was generated from the following file:
AStarRouter.h