SUMO - Simulation of Urban MObility: ROJTRRouter Class Reference
ROJTRRouter Class Reference
Computes routes using junction turning percentages.
#include <ROJTRRouter.h>
Public Member Functions
void endQuery (int visits)
virtual void prepare (const ROEdge *, const ROVehicle *, bool)
ROJTRRouter (RONet &net, bool unbuildIsWarningOnly, bool acceptAllDestinations, int maxEdges, bool ignoreClasses, bool allowLoops)
Constructor.
void startQuery ()
~ROJTRRouter ()
Destructor.
Implementatios of SUMOAbstractRouter
void compute (const ROEdge *from, const ROEdge *to, const ROVehicle *const vehicle, SUMOTime time, std::vector< const ROEdge * > &into)
Computes a route.
SUMOReal recomputeCosts (const std::vector< const ROEdge * > &edges, const ROVehicle *const v, SUMOTime time) const
Recomputes the costs of a route.
Private Attributes
const bool myAcceptAllDestination
Whether all edges may be used as route end.
const bool myAllowLoops
Whether a vehicle may reuse a road.
const bool myIgnoreClasses
Whether vehicle class information shall be ignored.
const int myMaxEdges
The maximum number of edges a route may have.
RONet & myNet
The network to use.
const bool myUnbuildIsWarningOnly
Whether unbuildable routes shall be reported as warniings, not errors.
Detailed Description
Computes routes using junction turning percentages.
Definition at line 52 of file ROJTRRouter.h.
Constructor & Destructor Documentation
ROJTRRouter::ROJTRRouter (RONet & net, bool unbuildIsWarningOnly, bool acceptAllDestinations, int maxEdges, bool ignoreClasses, bool allowLoops)
Constructor.
Parameters
[in] net The net used for routing
[in] unbuildIsWarningOnly Whether not closed routes shall not yield in an error
[in] acceptAllDestinations If false, only sinks will be used as final edges
[in] maxEdges The maximum number of edges a route may have
[in] ignoreClasses Whether routing shall be done without regarding vehicle classes
[in] allowLoops Whether a vehicle may reuse a road
Definition at line 46 of file ROJTRRouter.cpp.
ROJTRRouter::~ROJTRRouter ()
Destructor.
Definition at line 55 of file ROJTRRouter.cpp.
Member Function Documentation
void ROJTRRouter::compute (const ROEdge * from, const ROEdge * to, const ROVehicle *const vehicle, SUMOTime time, std::vector< const ROEdge * > & into) virtual
Computes a route.
The description how routes are computed is given in the user documentation
Parameters
[in] from The edge the vehicle starts at
[in] to The destination edge - invalid here
[in] vehicle The vehicle to compute the route for
[in] time The departure time of the vehicle
filled] into The list of edges to store the route into
Implements SUMOAbstractRouter< ROEdge, ROVehicle >.
Definition at line 59 of file ROJTRRouter.cpp.
References ROJTREdge::chooseNext(), ROEdge::ET_SINK, MsgHandler::getErrorInstance(), Named::getID(), ROEdge::getTravelTime(), ROEdge::getType(), MsgHandler::getWarningInstance(), MsgHandler::inform(), myAcceptAllDestination, myIgnoreClasses, myMaxEdges, myUnbuildIsWarningOnly, and ROEdge::prohibits().
void SUMOAbstractRouter< ROEdge , ROVehicle >::endQuery (int visits) inline inherited
Definition at line 90 of file SUMOAbstractRouter.h.
virtual void SUMOAbstractRouter< ROEdge , ROVehicle >::prepare (const ROEdge * , const ROVehicle * , bool) inline virtual inherited
Definition at line 81 of file SUMOAbstractRouter.h.
SUMOReal ROJTRRouter::recomputeCosts (const std::vector< const ROEdge * > & edges, const ROVehicle *const v, SUMOTime time) const virtual
Recomputes the costs of a route.
Parameters
[in] edges The route
[in] v The vehicle that belongs to the route
[in] time The departure time of the vehicle
Returns
The route costs
Implements SUMOAbstractRouter< ROEdge, ROVehicle >.
Definition at line 92 of file ROJTRRouter.cpp.
References SUMOReal.
void SUMOAbstractRouter< ROEdge , ROVehicle >::startQuery () inline inherited
Definition at line 85 of file SUMOAbstractRouter.h.
Field Documentation
const bool ROJTRRouter::myAcceptAllDestination private
Whether all edges may be used as route end.
Definition at line 106 of file ROJTRRouter.h.
Referenced by compute().
const bool ROJTRRouter::myAllowLoops private
Whether a vehicle may reuse a road.
Definition at line 115 of file ROJTRRouter.h.
const bool ROJTRRouter::myIgnoreClasses private
Whether vehicle class information shall be ignored.
Definition at line 112 of file ROJTRRouter.h.
Referenced by compute().
const int ROJTRRouter::myMaxEdges private
The maximum number of edges a route may have.
Definition at line 109 of file ROJTRRouter.h.
Referenced by compute().
RONet& ROJTRRouter::myNet private
The network to use.
Definition at line 100 of file ROJTRRouter.h.
const bool ROJTRRouter::myUnbuildIsWarningOnly private
Whether unbuildable routes shall be reported as warniings, not errors.
Definition at line 103 of file ROJTRRouter.h.
Referenced by compute().
The documentation for this class was generated from the following files:
ROJTRRouter.h
ROJTRRouter.cpp