SUMO - Simulation of Urban MObility: ROCostCalculator Class Reference
ROCostCalculator Class Reference abstract
Abstract base class providing static factory method.
#include <ROCostCalculator.h>
Public Member Functions
virtual void calculateProbabilities (std::vector< RORoute * > alternatives, const ROVehicle *const veh, const SUMOTime time)=0
calculate the probabilities in the logit model
unsigned int getMaxRouteNumber () const
bool keepRoutes () const
virtual void setCosts (RORoute *route, const SUMOReal costs, const bool isActive=false) const =0
bool skipRouteCalculation () const
Static Public Member Functions
static void cleanup ()
static ROCostCalculator & getCalculator ()
Protected Member Functions
ROCostCalculator ()
Constructor.
virtual ~ROCostCalculator ()
Destructor.
Private Attributes
bool myKeepRoutes
Information whether all routes should be saved.
unsigned int myMaxRouteNumber
The maximum route alternatives number.
bool mySkipRouteCalculation
Information whether new routes should be calculated.
Static Private Attributes
static ROCostCalculator * myInstance = 0
Detailed Description
Abstract base class providing static factory method.
Definition at line 53 of file ROCostCalculator.h.
Constructor & Destructor Documentation
ROCostCalculator::ROCostCalculator () protected
Constructor.
Definition at line 57 of file ROCostCalculator.cpp.
References OptionsCont::getBool(), OptionsCont::getInt(), OptionsCont::getOptions(), myKeepRoutes, myMaxRouteNumber, and mySkipRouteCalculation.
ROCostCalculator::~ROCostCalculator () protected virtual
Destructor.
Definition at line 65 of file ROCostCalculator.cpp.
Member Function Documentation
virtual void ROCostCalculator::calculateProbabilities (std::vector< RORoute * > alternatives, const ROVehicle *const veh, const SUMOTime time) pure virtual
calculate the probabilities in the logit model
Implemented in ROLogitCalculator, and ROGawronCalculator.
Referenced by RORouteDef::addAlternative().
void ROCostCalculator::cleanup () static
Definition at line 83 of file ROCostCalculator.cpp.
References myInstance.
Referenced by computeRoutes().
ROCostCalculator & ROCostCalculator::getCalculator () static
Definition at line 69 of file ROCostCalculator.cpp.
References OptionsCont::getFloat(), OptionsCont::getOptions(), OptionsCont::getString(), and myInstance.
Referenced by RORouteDef::addAlternative(), and RORouteDef::preComputeCurrentRoute().
unsigned int ROCostCalculator::getMaxRouteNumber () const inline
Definition at line 64 of file ROCostCalculator.h.
References myMaxRouteNumber.
Referenced by RORouteDef::addAlternative().
bool ROCostCalculator::keepRoutes () const inline
Definition at line 68 of file ROCostCalculator.h.
References myKeepRoutes.
Referenced by RORouteDef::addAlternative().
virtual void ROCostCalculator::setCosts (RORoute * route, const SUMOReal costs, const bool isActive = false) const pure virtual
Implemented in ROLogitCalculator, and ROGawronCalculator.
Referenced by RORouteDef::addAlternative().
bool ROCostCalculator::skipRouteCalculation () const inline
Definition at line 72 of file ROCostCalculator.h.
References mySkipRouteCalculation.
Field Documentation
ROCostCalculator * ROCostCalculator::myInstance = 0 static private
Definition at line 84 of file ROCostCalculator.h.
Referenced by cleanup(), and getCalculator().
bool ROCostCalculator::myKeepRoutes private
Information whether all routes should be saved.
Definition at line 90 of file ROCostCalculator.h.
Referenced by keepRoutes(), and ROCostCalculator().
unsigned int ROCostCalculator::myMaxRouteNumber private
The maximum route alternatives number.
Definition at line 87 of file ROCostCalculator.h.
Referenced by getMaxRouteNumber(), and ROCostCalculator().
bool ROCostCalculator::mySkipRouteCalculation private
Information whether new routes should be calculated.
Definition at line 93 of file ROCostCalculator.h.
Referenced by ROCostCalculator(), and skipRouteCalculation().
The documentation for this class was generated from the following files:
ROCostCalculator.h
ROCostCalculator.cpp