SUMO - Simulation of Urban MObility: MSEdge Class Reference
MSEdge Class Reference
A road/street connecting two junctions.
#include <MSEdge.h>
Data Structures
class by_id_sorter
Sorts edges by their ids.
class person_by_offset_sorter
Sorts edges by their ids.
Public Types
typedef std::map< const MSEdge
*, std::vector< MSLane * > * > AllowedLanesCont
Suceeding edges (keys) and allowed lanes to reach these edges (values).
typedef std::map
< SUMOVehicleClass,
AllowedLanesCont > ClassedAllowedLanesCont
Map from vehicle types to lanes that may be used to reach one of the next edges.
enum EdgeBasicFunction {
EDGEFUNCTION_UNKNOWN = -1, EDGEFUNCTION_NORMAL = 0, EDGEFUNCTION_CONNECTOR = 1, EDGEFUNCTION_INTERNAL = 2,
EDGEFUNCTION_DISTRICT = 3, EDGEFUNCTION_CROSSING = 4, EDGEFUNCTION_WALKINGAREA = 5
}
Defines possible edge types.
Public Member Functions
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
virtual void addPerson (MSPerson *p) const
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
virtual void changeLanes (SUMOTime t)
Performs lane changing on this edge.
void clearParameter ()
Clears the parameter map.
void closeBuilding ()
SUMOReal getCurrentTravelTime (const SUMOReal minSpeed=0.00001) const
Computes and returns the current travel time for this edge.
SUMOReal getDistanceTo (const MSEdge *other) const
optimistic air distance heuristic for use in routing
const std::string & getID () const
Returns the id.
SUMOReal getLength () const
return the length of the edge
const std::map< std::string,
std::string > & getMap () const
Returns the inner key/value map.
SUMOReal getMinimumTravelTime (const SUMOVehicle *const veh) const
returns the minimum travel time for the given vehicle
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
SUMOReal getSpeedLimit () const
Returns the speed limit of the edge The speed limit of the first lane is retured; should probably be the fastest edge.
SUMOReal getVehicleMaxSpeed (const SUMOVehicle *const veh) const
Returns the maximum speed the vehicle may use on this edge.
void initialize (std::vector< MSLane * > *lanes)
Initialize the edge.
bool isRoundabout () const
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
bool laneChangeAllowed () const
whether lane changing may be performed on this edge
void markAsRoundabout ()
MSEdge (const std::string &id, int numericalID, const EdgeBasicFunction function, const std::string &streetName="", const std::string &edgeType="")
Constructor.
bool prohibits (const SUMOVehicle *const vehicle) const
Returns whether the vehicle (class) is not allowed on the edge.
void rebuildAllowedLanes ()
virtual void removePerson (MSPerson *p) const
void setID (const std::string &newID)
resets the id
virtual ~MSEdge ()
Destructor.
Access to the edge's lanes
MSLane * leftLane (const MSLane *const lane) const
Returns the lane left to the one given, 0 if the given lane is leftmost.
MSLane * rightLane (const MSLane *const lane) const
Returns the lane right to the one given, 0 if the given lane is rightmost.
MSLane * parallelLane (const MSLane *const lane, int offset) const
Returns the lane with the given offset parallel to the given lane one or 0 if it does not exist.
const std::vector< MSLane * > & getLanes () const
Returns this edge's lanes.
std::vector< MSPerson * > getSortedPersons (SUMOTime timestep) const
Returns this edge's persons sorted by pos.
const std::vector< MSLane * > * allowedLanes (const MSEdge &destination, SUMOVehicleClass vclass=SVC_IGNORING) const
Get the allowed lanes to reach the destination-edge.
const std::vector< MSLane * > * allowedLanes (SUMOVehicleClass vclass=SVC_IGNORING) const
Get the allowed lanes for the given vehicle class.
Access to other edge attributes
EdgeBasicFunction getPurpose () const
Returns the edge type (EdgeBasicFunction)
bool isInternal () const
return whether this edge is an internal edge
bool isCrossing () const
return whether this edge is a pedestrian crossing
bool isWalkingArea () const
return whether this edge is walking area
int getNumericalID () const
Returns the numerical id of the edge.
const std::string & getStreetName () const
Returns the street name of the edge.
const std::string & getEdgeType () const
Returns the type of the edge.
Access to succeeding/predecessing edges
void addFollower (MSEdge *edge)
Returns the list of edges which may be reached from this edge.
const std::vector< MSEdge * > & getIncomingEdges () const
Returns the list of edges from which this edge may be reached.
unsigned int getNoFollowing () const
Returns the number of edges that may be reached from this edge.
const MSEdge * getFollower (unsigned int n) const
Returns the n-th of the following edges.
const MSJunction * getFromJunction () const
const MSJunction * getToJunction () const
void setJunctions (MSJunction *from, MSJunction *to)
Access to vaporizing interface
bool isVaporizing () const
Returns whether vehicles on this edge shall be vaporized.
SUMOTime incVaporization (SUMOTime t)
Enables vaporization.
SUMOTime decVaporization (SUMOTime t)
Disables vaporization.
Methods releated to vehicle insertion
bool insertVehicle (SUMOVehicle &v, SUMOTime time) const
Tries to insert the given vehicle into the network.
MSLane * getFreeLane (const std::vector< MSLane * > *allowed, const SUMOVehicleClass vclass) const
Finds the emptiest lane allowing the vehicle class.
MSLane * getDepartLane (const MSVehicle &veh) const
Finds a depart lane for the given vehicle parameters.
SUMOTime getLastFailedInsertionTime () const
Returns the last time a vehicle could not be inserted.
void setLastFailedInsertionTime (SUMOTime time) const
Sets the last time a vehicle could not be inserted.
Static Public Member Functions
static void clear ()
Clears the dictionary.
static bool dictionary (const std::string &id, MSEdge *edge)
Inserts edge into the static dictionary Returns true if the key id isn't already in the dictionary. Otherwise returns false.
static MSEdge * dictionary (const std::string &id)
Returns the MSEdge associated to the key id if exists, otherwise returns 0.
static MSEdge * dictionary (size_t index)
Returns the MSEdge at the index.
static size_t dictSize ()
Returns the number of edges.
static void insertIDs (std::vector< std::string > &into)
Inserts IDs of all known edges into the given vector.
static size_t numericalDictSize ()
Returns the number of edges with a numerical id.
Static parser helper
static void parseEdgesList (const std::string &desc, std::vector< const MSEdge * > &into, const std::string &rid)
Parses the given string assuming it contains a list of edge ids divided by spaces.
static void parseEdgesList (const std::vector< std::string > &desc, std::vector< const MSEdge * > &into, const std::string &rid)
Parses the given string vector assuming it edge ids.
Protected Member Functions
const std::vector< MSLane * > * allowedLanes (const MSEdge *destination, SUMOVehicleClass vclass=SVC_IGNORING) const
Get the allowed lanes to reach the destination-edge.
const std::vector< MSLane * > * getAllowedLanesWithDefault (const AllowedLanesCont &c, const MSEdge *dest) const
lookup in map and return 0 if not found
Protected Attributes
bool myAmRoundabout
whether this edge belongs to a roundabout
std::string myEdgeType
the type of the edge (optionally used during network creation)
MSJunction * myFromJunction
the junctions for this edge
const EdgeBasicFunction myFunction
the purpose of the edge
std::string myID
The name of the object.
MSLaneChanger * myLaneChanger
This member will do the lane-change.
std::vector< MSLane * > * myLanes
Container for the edge's lane; should be sorted: (right-hand-traffic) the more left the lane, the higher the container-index.
SUMOTime myLastFailedInsertionTime
The time of last insertion failure.
int myNumericalID
This edge's numerical id.
std::set< MSPerson * > myPersons
Persons on the edge (only for drawing)
std::vector< MSEdge * > myPredeccesors
The preceeding edges.
std::string myStreetName
the real-world name of this edge (need not be unique)
std::vector< MSEdge * > mySuccessors
The succeeding edges.
MSJunction * myToJunction
int myVaporizationRequests
Vaporizer counter.
Storages for allowed lanes (depending on vehicle classes)
AllowedLanesCont myAllowed
Associative container from destination-edge to allowed-lanes.
ClassedAllowedLanesCont myClassedAllowed
From vehicle class to lanes allowed to be used by it.
SVCPermissions myMinimumPermissions
The intersection of lane permissions for this edge.
SVCPermissions myCombinedPermissions
The union of lane permissions for this edge.
Private Member Functions
MSEdge (const MSEdge &)
Invalidated copy constructor.
MSEdge & operator= (const MSEdge &)
assignment operator.
Static edge container
typedef std::map< std::string,
MSEdge * > DictType
definition of the static dictionary type
static DictType myDict
Static dictionary to associate string-ids with objects.
static std::vector< MSEdge * > myEdges
Static list of edges.
Detailed Description
A road/street connecting two junctions.
A single connection between two junctions. Holds lanes which are reponsible for vehicle movements.
Definition at line 74 of file MSEdge.h.
Member Typedef Documentation
typedef std::map< const MSEdge*, std::vector<MSLane*>* > MSEdge::AllowedLanesCont
Suceeding edges (keys) and allowed lanes to reach these edges (values).
Definition at line 102 of file MSEdge.h.
typedef std::map< SUMOVehicleClass, AllowedLanesCont > MSEdge::ClassedAllowedLanesCont
Map from vehicle types to lanes that may be used to reach one of the next edges.
Definition at line 105 of file MSEdge.h.
typedef std::map< std::string, MSEdge* > MSEdge::DictType protected
definition of the static dictionary type
Definition at line 663 of file MSEdge.h.
Member Enumeration Documentation
enum MSEdge::EdgeBasicFunction
Defines possible edge types.
For different purposes, it is necessary to know whether the edge is a normal street or something special.
Enumerator
EDGEFUNCTION_UNKNOWN
The purpose of the edge is not known.
EDGEFUNCTION_NORMAL
The edge is a normal street.
EDGEFUNCTION_CONNECTOR
The edge is a macroscopic connector (source/sink)
EDGEFUNCTION_INTERNAL
The edge is an internal edge.
EDGEFUNCTION_DISTRICT
The edge is a district edge.
EDGEFUNCTION_CROSSING
The edge is a pedestrian crossing (a special type of internal edge)
EDGEFUNCTION_WALKINGAREA
The edge is a pedestrian walking area (a special type of internal edge)
Definition at line 83 of file MSEdge.h.
Constructor & Destructor Documentation
MSEdge::MSEdge (const std::string & id, int numericalID, const EdgeBasicFunction function, const std::string & streetName = "", const std::string & edgeType = "")
Constructor.
After calling this constructor, the edge is not yet initialised completely. A call to "initialize" with proper values is needed for this.
Parameters
[in] id The id of the edge
[in] numericalID The numerical id (index) of the edge
[in] function A basic type of the edge
[in] streetName The street name for that edge
Definition at line 71 of file MSEdge.cpp.
MSEdge::~MSEdge () virtual
Destructor.
Definition at line 84 of file MSEdge.cpp.
References myAllowed, myClassedAllowed, myLaneChanger, and myLanes.
MSEdge::MSEdge (const MSEdge &) private
Invalidated copy constructor.
Member Function Documentation
void MSEdge::addFollower (MSEdge * edge) inline
Returns the list of edges which may be reached from this edge.
Returns
Edges reachable from this edge
Definition at line 263 of file MSEdge.h.
References mySuccessors.
Referenced by NLHandler::addDistrict().
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 53 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NLHandler::addParam(), SUMORouteHandler::addParam(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenDrive::loadNetwork(), and NIImporter_MATSim::EdgesHandler::myStartElement().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 59 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 67 of file Parameterised.cpp.
References Parameterised::myMap.
virtual void MSEdge::addPerson (MSPerson * p) const inline virtual
Reimplemented in GUIEdge.
Definition at line 483 of file MSEdge.h.
References myPersons.
Referenced by GUIEdge::addPerson(), MSPerson::MSPersonStage_Driving::proceed(), and MSPerson::MSPersonStage_Waiting::proceed().
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
in,filled] cont The container to add this item to
Definition at line 121 of file Named.h.
References Named::StoringVisitor::add().
const std::vector< MSLane * > * MSEdge::allowedLanes (const MSEdge & destination, SUMOVehicleClass vclass = SVC_IGNORING) const
Get the allowed lanes to reach the destination-edge.
If there is no such edge, get 0. Then you are on the wrong edge.
Parameters
[in] destination The edge to reach
[in] vclass The vehicle class for which this information shall be returned
Returns
The lanes that may be used to reach the given edge, 0 if no such lanes exist
Definition at line 221 of file MSEdge.cpp.
Referenced by allowedLanes(), MSVehicleTransfer::checkInsertions(), getDepartLane(), getFreeLane(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSLane::by_connections_to_sorter::operator()(), and MSVehicle::updateBestLanes().
const std::vector< MSLane * > * MSEdge::allowedLanes (SUMOVehicleClass vclass = SVC_IGNORING) const
Get the allowed lanes for the given vehicle class.
If there is no such edge, get 0. Then you are on the wrong edge.
Parameters
[in] vclass The vehicle class for which this information shall be returned
Returns
The lanes that may be used by the given vclass
Definition at line 227 of file MSEdge.cpp.
References allowedLanes().
const std::vector< MSLane * > * MSEdge::allowedLanes (const MSEdge * destination, SUMOVehicleClass vclass = SVC_IGNORING) const protected
Get the allowed lanes to reach the destination-edge.
If there is no such edge, get 0. Then you are on the wrong edge.
Parameters
[in] destination The edge to reach
[in] vclass The vehicle class for which this information shall be returned
Returns
The lanes that may be used to reach the given edge, 0 if no such lanes exist
Definition at line 243 of file MSEdge.cpp.
References getAllowedLanesWithDefault(), myAllowed, myClassedAllowed, and myMinimumPermissions.
void MSEdge::changeLanes (SUMOTime t) virtual
Performs lane changing on this edge.
Definition at line 413 of file MSEdge.cpp.
References MSLaneChanger::laneChange(), laneChangeAllowed(), and myLaneChanger.
Referenced by MSEdgeControl::changeLanes().
void MSEdge::clear () static
Clears the dictionary.
Definition at line 519 of file MSEdge.cpp.
References myDict.
Referenced by MSNet::clearAll(), and MSVehicle::updateBestLanes().
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 91 of file Parameterised.cpp.
References Parameterised::myMap.
void MSEdge::closeBuilding ()
Todo:
Has to be called after all edges were built and all connections were set...; Still, is not very nice
Definition at line 134 of file MSEdge.cpp.
References MSLane::getEdge(), myAllowed, myLanes, myPredeccesors, mySuccessors, and rebuildAllowedLanes().
SUMOTime MSEdge::decVaporization (SUMOTime t)
Disables vaporization.
The internal vaporization counter is decreased what disables the vaporization if it was only once enabled. Called from the event handler.
Parameters
[in] t The current time (unused)
Returns
Time to next call (always 0)
Exceptions
ProcessError not thrown by this method, just derived
Definition at line 289 of file MSEdge.cpp.
References myVaporizationRequests.
Referenced by NLTriggerBuilder::buildVaporizer().
bool MSEdge::dictionary (const std::string & id, MSEdge * edge) static
Inserts edge into the static dictionary Returns true if the key id isn't already in the dictionary. Otherwise returns false.
Definition at line 473 of file MSEdge.cpp.
References getNumericalID(), myDict, and myEdges.
Referenced by NLHandler::addConnection(), NLHandler::addDistrict(), NLHandler::addDistrictEdge(), NLBuilder::EdgeFloatTimeLineRetriever_EdgeEffort::addEdgeWeight(), NLBuilder::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight(), NLHandler::addRoundabout(), NLEdgeControlBuilder::beginEdgeParsing(), NLTriggerBuilder::buildVaporizer(), MSDevice_Routing::buildVehicleDevices(), NLHandler::closeEdge(), TraCIServerAPI_Simulation::convertCartesianToRoadMap(), NLDetectorBuilder::getEdgeChecking(), TraCIServerAPI_Simulation::getLaneChecking(), TraCIServerAPI_Edge::getShape(), MSPModel_Striping::initWalkingAreaPaths(), NLHandler::myEndElement(), MSRouteHandler::myStartElement(), MSStateHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), GUIApplicationWindow::onCmdEditChosen(), NLTriggerBuilder::parseAndBuildRerouter(), parseEdgesList(), MSDevice_Routing::preInsertionReroute(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_Route::processSet(), TraCIServerAPI_Vehicle::processSet(), MSBaseVehicle::reroute(), MSStateHandler::saveState(), and TraCIServerAPI_Vehicle::vtdMap_matchingNearest().
MSEdge * MSEdge::dictionary (const std::string & id) static
Returns the MSEdge associated to the key id if exists, otherwise returns 0.
Definition at line 489 of file MSEdge.cpp.
References myDict.
MSEdge * MSEdge::dictionary (size_t index) static
Returns the MSEdge at the index.
Definition at line 500 of file MSEdge.cpp.
References myEdges.
size_t MSEdge::dictSize () static
Returns the number of edges.
Definition at line 507 of file MSEdge.cpp.
References myDict.
Referenced by GUIEdge::fill(), MSPModel_Striping::initWalkingAreaPaths(), GUIApplicationWindow::onCmdEditChosen(), and MSStateHandler::saveState().
const std::vector< MSLane * > * MSEdge::getAllowedLanesWithDefault (const AllowedLanesCont & c, const MSEdge * dest) const protected
lookup in map and return 0 if not found
Definition at line 233 of file MSEdge.cpp.
Referenced by allowedLanes().
SUMOReal MSEdge::getCurrentTravelTime (const SUMOReal minSpeed = 0.00001) const
Computes and returns the current travel time for this edge.
The mean speed of all lanes is used to compute the travel time. To avoid infinite travel times, the given minimum speed is used.
Parameters
[in] minSpeed The minimumSpeed to assume if traffic on this edge is stopped
Returns
The current effort (travel time) to pass the edge
Definition at line 445 of file MSEdge.cpp.
References getLength(), MSGlobals::gUseMesoSim, MAX2(), myLanes, and SUMOReal.
Referenced by MSVehicleTransfer::add(), MSVehicleTransfer::checkInsertions(), TraCIServerAPI_Edge::processGet(), and MSFullExport::writeEdge().
MSLane * MSEdge::getDepartLane (const MSVehicle & veh) const
Finds a depart lane for the given vehicle parameters.
Depending on the depart lane procedure a depart lane is chosen. Repeated calls with the same vehicle may return different results if the procedure is "random" or "free". In case no appropriate lane was found, 0 is returned.
Parameters
[in] veh The vehicle to get the depart lane for
Returns
a possible/chosen depart lane, 0 if no lane can be used
Definition at line 315 of file MSEdge.cpp.
References allowedLanes(), MSRoute::begin(), DEPART_LANE_ALLOWED_FREE, DEPART_LANE_BEST_FREE, DEPART_LANE_DEFAULT, DEPART_LANE_FREE, DEPART_LANE_GIVEN, DEPART_LANE_RANDOM, SUMOVehicleParameter::departLane, SUMOVehicleParameter::departLaneProcedure, MSVehicle::getBestLanes(), getFreeLane(), MSBaseVehicle::getParameter(), RandHelper::getRandomFrom(), MSBaseVehicle::getRoute(), MSVehicleType::getVehicleClass(), MSBaseVehicle::getVehicleType(), myLanes, MSRoute::size(), and SUMOReal.
Referenced by insertVehicle().
SUMOReal MSEdge::getDistanceTo (const MSEdge * other) const
optimistic air distance heuristic for use in routing
Parameters
[in] other The edge to which the distance shall be returned
Returns
The distance to the other edge
Definition at line 566 of file MSEdge.cpp.
References getLanes().
const std::string& MSEdge::getEdgeType () const inline
Returns the type of the edge.
Definition at line 250 of file MSEdge.h.
References myEdgeType.
Referenced by GUILane::getParameterWindow().
const MSEdge* MSEdge::getFollower (unsigned int n) const inline
Returns the n-th of the following edges.
Parameters
[in] n The index within following edges of the edge to return
Returns
The n-th of the following edges
Definition at line 288 of file MSEdge.h.
References mySuccessors.
Referenced by NLEdgeControlBuilder::build(), MSLane::getInternalFollower(), MSPModel_Striping::initWalkingAreaPaths(), and MSRouteHandler::myStartElement().
MSLane * MSEdge::getFreeLane (const std::vector< MSLane * > * allowed, const SUMOVehicleClass vclass) const
Finds the emptiest lane allowing the vehicle class.
The emptiest lane is the one with the fewest vehicles on. If there is more than one, the first according to its index in the lane container is chosen.
If allowed==0, the lanes allowed for the given vehicle class will be used.
Parameters
[in] allowed The lanes to choose from
[in] vclass The vehicle class to look for
Returns
the least occupied lane
See Also
allowedLanes
Definition at line 296 of file MSEdge.cpp.
References allowedLanes(), and MSLane::getVehicleNumber().
Referenced by MSVehicleTransfer::checkInsertions(), and getDepartLane().
const MSJunction* MSEdge::getFromJunction () const inline
Definition at line 293 of file MSEdge.h.
References myFromJunction.
Referenced by MSPModel::canTraverse(), MSPModel_NonInteracting::PState::computeWalkingTime(), MSPModel_Striping::getNextLane(), and MSPModel_Striping::PState::PState().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 60 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), Named::StoringVisitor::add(), MSDetectorControl::add(), RORouteDef::addAlternative(), MSNet::addBusStop(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), NBNode::buildCrossings(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), NBNode::buildInnerEdges(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), NBNode::buildWalkingAreas(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBTrafficLightDefinition::collectEdges(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), NLDetectorBuilder::convUncontE2PosLength(), GUINet::createTLWrapper(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSE3Collector::enter(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSNet::getBusStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), PedestrianEdge< E, L, N >::getEffort(), NBEdge::getFirstNonPedestrianLane(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), AGStreet::getName(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPModel_Striping::getNextLane(), GUIVehicle::getParameterWindow(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), NBEdgeCont::ignoreFilterMatch(), MSActuatedTrafficLightLogic::init(), MSAgentbasedTrafficLightLogic::init(), MSTrafficLightLogic::init(), PedestrianEdge< E, L, N >::initPedestrianNetwork(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), RODFNet::isDestination(), RODFNet::isFalseSource(), RODFNet::isSource(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Person::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), GUIViewTraffic::onGamingClick(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_JE2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSRightOfWayJunction::postloadInit(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBNodeCont::rename(), NBEdgeCont::rename(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), PCPolyContainer::save(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), NIXMLEdgesHandler::setNodes(), MSLink::setRequestInformation(), NBOwnTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap_matchingEdgeLane(), TraCIServerAPI_Vehicle::vtdMap_matchingRoutePosition(), MSLCM_JE2013::wantsChange(), MSFCDExport::write(), MSEmissionExport::write(), MSInstantInductLoop::write(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const std::vector<MSEdge*>& MSEdge::getIncomingEdges () const inline
Returns the list of edges from which this edge may be reached.
Returns
Edges from which this edge may be reached
Definition at line 271 of file MSEdge.h.
References myPredeccesors.
Referenced by NLEdgeControlBuilder::build(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSLane::getLogicalPredecessorLane(), and MSPModel_Striping::initWalkingAreaPaths().
const std::vector<MSLane*>& MSEdge::getLanes () const inline
Returns this edge's lanes.
Returns
This edge's lanes
Definition at line 173 of file MSEdge.h.
References myLanes.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSVehicleTransfer::add(), NLHandler::addConnection(), MSBaseVehicle::calculateArrivalPos(), MSEdgeControl::changeLanes(), MSVehicleTransfer::checkInsertions(), GUILane::drawMarkings(), MSCalibrator::execute(), MS_E2_ZS_CollectorOverLanes::extendTo(), getDistanceTo(), MSPerson::MSPersonStage::getEdgeAngle(), GUILane::getEdgeLaneNumber(), MSPerson::MSPersonStage::getEdgePosition(), TraCIServerAPI_Simulation::getLaneChecking(), MSVehicle::getLaneIndex(), getLength(), GUIEdge::getPopUpMenu(), MSVehicle::getPosition(), TraCIServerAPI_Edge::getShape(), MSPModel::getSidewalk(), getSpeedLimit(), getVehicleMaxSpeed(), GUICalibrator::GUICalibrator(), GUITriggeredRerouter::GUITriggeredRerouterEdge::GUITriggeredRerouterEdge(), MSVehicle::Influencer::influenceChangeDecision(), GUINet::initGUIStructures(), MSCalibrator::invalidJam(), GUISUMOViewParent::isSelected(), MSCalibrator::MSCalibrator(), MSRouteProbe::MSRouteProbe(), MSLCM_DK2008::patchSpeed(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_Vehicle::processSet(), MSCalibrator::remainingVehicleCapacity(), MSVehicle::updateBestLanes(), TraCIServerAPI_Vehicle::vtdMap_matchingNearest(), TraCIServerAPI_Vehicle::vtdMap_matchingRoutePosition(), MSQueueExport::writeEdge(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), and MSMeanData::writeEdge().
SUMOTime MSEdge::getLastFailedInsertionTime () const inline
Returns the last time a vehicle could not be inserted.
Returns
The current value
Definition at line 419 of file MSEdge.h.
References myLastFailedInsertionTime.
SUMOReal MSEdge::getLength () const
return the length of the edge
Returns
The edge's length
Definition at line 576 of file MSEdge.cpp.
References getLanes().
Referenced by NLTriggerBuilder::buildCalibrator(), MSPModel_NonInteracting::PState::computeWalkingTime(), getCurrentTravelTime(), MSPerson::MSPersonStage_Driving::getEdgePos(), getMinimumTravelTime(), MSPModel_Striping::getNextLane(), GUIEdge::getParameterWindow(), insertVehicle(), MSCalibrator::MSCalibrator(), MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting(), MSCalibrator::remainingVehicleCapacity(), MSVehicle::updateBestLanes(), and MSMeanData::writeEdge().
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 107 of file Parameterised.h.
References Parameterised::myMap.
Referenced by NBTrafficLightDefinition::compute(), GUIVehicle::getParameterWindow(), and PCPolyContainer::save().
SUMOReal MSEdge::getMinimumTravelTime (const SUMOVehicle *const veh) const inline
returns the minimum travel time for the given vehicle
Definition at line 358 of file MSEdge.h.
References getLength(), SUMOVehicle::getMaxSpeed(), getSpeedLimit(), getVehicleMaxSpeed(), and MIN2().
Referenced by MSDevice_Routing::getEffort(), and MSNet::getTravelTime().
unsigned int MSEdge::getNoFollowing () const inline
Returns the number of edges that may be reached from this edge.
Returns
The number of following edges
Definition at line 279 of file MSEdge.h.
References mySuccessors.
Referenced by NLEdgeControlBuilder::build(), MSPModel_Striping::initWalkingAreaPaths(), and MSRouteHandler::myStartElement().
int MSEdge::getNumericalID () const inline
Returns the numerical id of the edge.
Returns
This edge's numerical id
Definition at line 237 of file MSEdge.h.
References myNumericalID.
Referenced by MSEdgeControl::changeLanes(), dictionary(), MSMeanData_Amitran::getEdgeID(), and MSDevice_Routing::getEffort().
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 81 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSAgentbasedTrafficLightLogic::MSAgentbasedTrafficLightLogic(), and TraCIServerAPI_Vehicle::vtdMap_matchingNearest().
EdgeBasicFunction MSEdge::getPurpose () const inline
Returns the edge type (EdgeBasicFunction)
Returns
This edge's EdgeBasicFunction
See Also
EdgeBasicFunction
Definition at line 215 of file MSEdge.h.
References myFunction.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLane::appropriate(), MSVehicle::checkRewindLinkLanes(), GUILane::drawGL(), MSVehicle::enterLaneAtMove(), MSVehicle::getBestLanesContinuation(), GUIEdge::getIDs(), MSLane::getInternalFollower(), MSLink::lastWasContMajor(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSLane::succLinkSec(), MSVehicle::updateBestLanes(), TraCIServerAPI_Vehicle::vtdMap_matchingEdgeLane(), TraCIServerAPI_Vehicle::vtdMap_matchingNearest(), TraCIServerAPI_Vehicle::vtdMap_matchingRoutePosition(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
std::vector< MSPerson * > MSEdge::getSortedPersons (SUMOTime timestep) const
Returns this edge's persons sorted by pos.
Returns
This edge's persons sorted by pos
Definition at line 596 of file MSEdge.cpp.
References myPersons.
Referenced by MSXMLRawOut::writeEdge().
SUMOReal MSEdge::getSpeedLimit () const
Returns the speed limit of the edge The speed limit of the first lane is retured; should probably be the fastest edge.
Returns
The maximum speed allowed on this edge
Definition at line 582 of file MSEdge.cpp.
References getLanes().
Referenced by GUIApplicationWindow::checkGamingEvents(), getMinimumTravelTime(), MSCalibrator::invalidJam(), MSCalibrator::remainingVehicleCapacity(), and MSMeanData::writeEdge().
const std::string& MSEdge::getStreetName () const inline
Returns the street name of the edge.
Definition at line 244 of file MSEdge.h.
References myStreetName.
Referenced by GUIEdge::drawGL(), and GUILane::getParameterWindow().
const MSJunction* MSEdge::getToJunction () const inline
Definition at line 297 of file MSEdge.h.
References myToJunction.
Referenced by MSPModel::canTraverse(), MSPModel_NonInteracting::PState::computeWalkingTime(), MSPModel_Striping::getNextLane(), and MSPModel_Striping::PState::PState().
SUMOReal MSEdge::getVehicleMaxSpeed (const SUMOVehicle *const veh) const
Returns the maximum speed the vehicle may use on this edge.
Note that the vehicle's max. speed is not considered herein, only the edge's speed limit and the driver's adaptation of this speed. Only the first lane is considered
Returns
The maximum velocity on this edge for the given vehicle
Definition at line 589 of file MSEdge.cpp.
References getLanes().
Referenced by getMinimumTravelTime().
SUMOTime MSEdge::incVaporization (SUMOTime t)
Enables vaporization.
The internal vaporization counter is increased enabling the vaporization. Called from the event handler.
Parameters
[in] t The current time (unused)
Returns
Time to next call (always 0)
Exceptions
ProcessError not thrown by this method, just derived
Definition at line 282 of file MSEdge.cpp.
References myVaporizationRequests.
Referenced by NLTriggerBuilder::buildVaporizer().
void MSEdge::initialize (std::vector< MSLane * > * lanes)
Initialize the edge.
Parameters
[in] allowed Information which edges may be reached from which lanes
[in] lanes List of this edge's lanes
Definition at line 100 of file MSEdge.cpp.
References EDGEFUNCTION_DISTRICT, OptionsCont::getOptions(), myCombinedPermissions, myFunction, myLaneChanger, myLanes, and SVCAll.
Referenced by NLHandler::addDistrict(), and NLEdgeControlBuilder::closeEdge().
void MSEdge::insertIDs (std::vector< std::string > & into) static
Inserts IDs of all known edges into the given vector.
Definition at line 528 of file MSEdge.cpp.
References myDict.
Referenced by TraCIServerAPI_Edge::processGet().
bool MSEdge::insertVehicle (SUMOVehicle & v, SUMOTime time) const
Tries to insert the given vehicle into the network.
The procedure for choosing the proper lane is determined, first. In dependance to this, the proper lane is chosen.
Insertion itself is done by calling the chose lane's "insertVehicle" method.
Parameters
[in] v The vehicle to insert
[in] time The current simulation time
Returns
Whether the vehicle could be inserted
See Also
MSLane::insertVehicle
Definition at line 362 of file MSEdge.cpp.
References DEPART_POS_FREE, DEPART_POS_GIVEN, DEPART_POS_RANDOM, DEPART_POS_RANDOM_FREE, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, getDepartLane(), SUMOVehicle::getID(), getLength(), SUMOVehicle::getParameter(), MSGlobals::gUseMesoSim, MSLane::insertVehicle(), isVaporizing(), RandHelper::rand(), SUMOReal, toString(), UNUSED_PARAMETER, and WRITE_WARNING.
Referenced by MSCalibrator::execute().
bool MSEdge::isCrossing () const inline
return whether this edge is a pedestrian crossing
Definition at line 225 of file MSEdge.h.
References EDGEFUNCTION_CROSSING, and myFunction.
Referenced by MSPModel_Striping::getNextLane().
bool MSEdge::isInternal () const inline
return whether this edge is an internal edge
Definition at line 220 of file MSEdge.h.
References EDGEFUNCTION_INTERNAL, and myFunction.
Referenced by NLEdgeControlBuilder::build(), and MSPModel_Striping::getNextLane().
bool MSEdge::isRoundabout () const inline
Definition at line 494 of file MSEdge.h.
References myAmRoundabout.
Referenced by NLEdgeControlBuilder::build(), MSVehicle::checkRewindLinkLanes(), and MSVehicle::executeMove().
bool MSEdge::isVaporizing () const inline
Returns whether vehicles on this edge shall be vaporized.
Returns
Whether no vehicle shall be on this edge
Definition at line 316 of file MSEdge.h.
References myVaporizationRequests.
Referenced by MSVehicle::executeMove(), MSLane::executeMovements(), and insertVehicle().
bool MSEdge::isWalkingArea () const inline
return whether this edge is walking area
Definition at line 230 of file MSEdge.h.
References EDGEFUNCTION_WALKINGAREA, and myFunction.
Referenced by MSPModel_Striping::getNextLane(), MSPModel_Striping::initWalkingAreaPaths(), and MSPModel_Striping::PState::PState().
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 75 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), and TraCIServerAPI_Vehicle::vtdMap_matchingNearest().
bool MSEdge::laneChangeAllowed () const
whether lane changing may be performed on this edge
Definition at line 113 of file MSEdge.cpp.
References EDGEFUNCTION_INTERNAL, MSLinkContHelper::getConnectingLink(), MSLane::getLogicalPredecessorLane(), MSLink::havePriority(), myFunction, and myLanes.
Referenced by changeLanes().
MSLane * MSEdge::leftLane (const MSLane *const lane) const
Returns the lane left to the one given, 0 if the given lane is leftmost.
Parameters
[in] lane The lane right to the one to be returned
Returns
The lane left to the given, 0 if no such lane exists
Todo:
This method searches for the given in the container; probably, this could be done faster
Definition at line 194 of file MSEdge.cpp.
References parallelLane().
void MSEdge::markAsRoundabout () inline
Definition at line 498 of file MSEdge.h.
References myAmRoundabout.
Referenced by NLHandler::addRoundabout(), and NLEdgeControlBuilder::build().
size_t MSEdge::numericalDictSize () static
Returns the number of edges with a numerical id.
Definition at line 513 of file MSEdge.cpp.
References myEdges.
Referenced by MSDevice_Routing::getRouter(), MSNet::getRouterEffort(), and MSNet::getRouterTT().
MSEdge& MSEdge::operator= (const MSEdge &) private
assignment operator.
MSLane * MSEdge::parallelLane (const MSLane *const lane, int offset) const
Returns the lane with the given offset parallel to the given lane one or 0 if it does not exist.
Parameters
[in] lane The base lane
[in] offset The offset of the result lane
Todo:
This method searches for the given in the container; probably, this could be done faster
Definition at line 206 of file MSEdge.cpp.
References myLanes.
Referenced by MSLane::getParallelLane(), leftLane(), and rightLane().
void MSEdge::parseEdgesList (const std::string & desc, std::vector< const MSEdge * > & into, const std::string & rid) static
Parses the given string assuming it contains a list of edge ids divided by spaces.
Splits the string at spaces, uses polymorph method to generate edge vector.
Parameters
[in] desc The string containing space-separated edge ids
[out] into The vector to fill
[in] rid The id of the route these description belongs to; used for error message generation
Exceptions
ProcessError If one of the strings contained is not a known edge id
Definition at line 536 of file MSEdge.cpp.
References BinaryFormatter::BF_ROUTE, StringTokenizer::getVector(), and FileHelpers::readEdgeVector().
Referenced by MSRouteHandler::myStartElement(), MSStateHandler::myStartElement(), MSRouteHandler::openRoute(), and TraCIServerAPI_Vehicle::processSet().
void MSEdge::parseEdgesList (const std::vector< std::string > & desc, std::vector< const MSEdge * > & into, const std::string & rid) static
Parses the given string vector assuming it edge ids.
Parameters
[in] desc The string vector containing edge ids
[out] into The vector to fill
[in] rid The id of the route these description belongs to; used for error message generation
Exceptions
ProcessError If one of the strings contained is not a known edge id
Definition at line 551 of file MSEdge.cpp.
References dictionary().
bool MSEdge::prohibits (const SUMOVehicle *const vehicle) const inline
Returns whether the vehicle (class) is not allowed on the edge.
Definition at line 443 of file MSEdge.h.
References MSVehicleType::getVehicleClass(), SUMOVehicle::getVehicleType(), and myCombinedPermissions.
void MSEdge::rebuildAllowedLanes ()
Definition at line 173 of file MSEdge.cpp.
References myClassedAllowed, myCombinedPermissions, myLanes, myMinimumPermissions, and SVCAll.
Referenced by closeBuilding(), TraCIServerAPI_Edge::processSet(), and TraCIServerAPI_Lane::processSet().
virtual void MSEdge::removePerson (MSPerson * p) const inline virtual
Reimplemented in GUIEdge.
Definition at line 487 of file MSEdge.h.
References myPersons.
Referenced by MSPersonControl::abortWaiting(), MSPersonControl::boardAnyWaiting(), MSPerson::MSPersonStage_Walking::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSPerson::proceed(), and GUIEdge::removePerson().
MSLane * MSEdge::rightLane (const MSLane *const lane) const
Returns the lane right to the one given, 0 if the given lane is rightmost.
Parameters
[in] lane The lane left to the one to be returned
Returns
The lane right to the given, 0 if no such lane exists
Todo:
This method searches for the given in the container; probably, this could be done faster
Definition at line 200 of file MSEdge.cpp.
References parallelLane().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 68 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::rename(), and NBEdgeCont::rename().
void MSEdge::setJunctions (MSJunction * from, MSJunction * to) inline
Definition at line 302 of file MSEdge.h.
References myFromJunction, and myToJunction.
Referenced by NLHandler::myEndElement().
void MSEdge::setLastFailedInsertionTime (SUMOTime time) const inline
Sets the last time a vehicle could not be inserted.
Parameters
[in] time the new value
Definition at line 427 of file MSEdge.h.
References myLastFailedInsertionTime.
Field Documentation
AllowedLanesCont MSEdge::myAllowed protected
Associative container from destination-edge to allowed-lanes.
Definition at line 638 of file MSEdge.h.
Referenced by allowedLanes(), closeBuilding(), and ~MSEdge().
bool MSEdge::myAmRoundabout protected
whether this edge belongs to a roundabout
Definition at line 657 of file MSEdge.h.
Referenced by isRoundabout(), and markAsRoundabout().
ClassedAllowedLanesCont MSEdge::myClassedAllowed mutable protected
From vehicle class to lanes allowed to be used by it.
Definition at line 642 of file MSEdge.h.
Referenced by allowedLanes(), rebuildAllowedLanes(), and ~MSEdge().
SVCPermissions MSEdge::myCombinedPermissions protected
The union of lane permissions for this edge.
Definition at line 647 of file MSEdge.h.
Referenced by initialize(), prohibits(), and rebuildAllowedLanes().
MSEdge::DictType MSEdge::myDict static protected
Static dictionary to associate string-ids with objects.
Deprecated:
Move to MSEdgeControl, make non-static
Definition at line 668 of file MSEdge.h.
Referenced by clear(), dictionary(), dictSize(), GUIEdge::fill(), GUIEdge::getIDs(), and insertIDs().
std::vector< MSEdge * > MSEdge::myEdges static protected
Static list of edges.
Deprecated:
Move to MSEdgeControl, make non-static
Definition at line 673 of file MSEdge.h.
Referenced by dictionary(), and numericalDictSize().
std::string MSEdge::myEdgeType protected
the type of the edge (optionally used during network creation)
Definition at line 654 of file MSEdge.h.
Referenced by getEdgeType().
MSJunction* MSEdge::myFromJunction protected
the junctions for this edge
Definition at line 628 of file MSEdge.h.
Referenced by getFromJunction(), and setJunctions().
const EdgeBasicFunction MSEdge::myFunction protected
the purpose of the edge
Definition at line 613 of file MSEdge.h.
Referenced by GUIEdge::drawGL(), getPurpose(), initialize(), isCrossing(), isInternal(), isWalkingArea(), and laneChangeAllowed().
std::string Named::myID protected inherited
The name of the object.
Definition at line 128 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), NBNode::computeNodeShape(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSAgentbasedTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSCalibrator::VehicleRemover::notifyEnter(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), RORouteDef::repairCurrentRoute(), Named::setID(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
MSLaneChanger* MSEdge::myLaneChanger protected
This member will do the lane-change.
Definition at line 610 of file MSEdge.h.
Referenced by changeLanes(), initialize(), and ~MSEdge().
std::vector<MSLane*>* MSEdge::myLanes protected
Container for the edge's lane; should be sorted: (right-hand-traffic) the more left the lane, the higher the container-index.
Definition at line 607 of file MSEdge.h.
Referenced by closeBuilding(), GUIEdge::drawGL(), GUIEdge::getBoundary(), getCurrentTravelTime(), getDepartLane(), getLanes(), GUIEdge::getParameterWindow(), initialize(), laneChangeAllowed(), parallelLane(), rebuildAllowedLanes(), and ~MSEdge().
SUMOTime MSEdge::myLastFailedInsertionTime mutable protected
The time of last insertion failure.
Definition at line 619 of file MSEdge.h.
Referenced by getLastFailedInsertionTime(), and setLastFailedInsertionTime().
SVCPermissions MSEdge::myMinimumPermissions protected
The intersection of lane permissions for this edge.
Definition at line 645 of file MSEdge.h.
Referenced by allowedLanes(), and rebuildAllowedLanes().
int MSEdge::myNumericalID protected
This edge's numerical id.
Definition at line 604 of file MSEdge.h.
Referenced by getNumericalID().
std::set<MSPerson*> MSEdge::myPersons mutable protected
Persons on the edge (only for drawing)
Definition at line 632 of file MSEdge.h.
Referenced by addPerson(), GUIEdge::drawGL(), getSortedPersons(), and removePerson().
std::vector<MSEdge*> MSEdge::myPredeccesors protected
The preceeding edges.
Definition at line 625 of file MSEdge.h.
Referenced by closeBuilding(), and getIncomingEdges().
std::string MSEdge::myStreetName protected
the real-world name of this edge (need not be unique)
Definition at line 651 of file MSEdge.h.
Referenced by GUIEdge::drawGL(), and getStreetName().
std::vector<MSEdge*> MSEdge::mySuccessors protected
The succeeding edges.
Definition at line 622 of file MSEdge.h.
Referenced by addFollower(), closeBuilding(), getFollower(), and getNoFollowing().
MSJunction* MSEdge::myToJunction protected
Definition at line 629 of file MSEdge.h.
Referenced by getToJunction(), and setJunctions().
int MSEdge::myVaporizationRequests protected
Vaporizer counter.
Definition at line 616 of file MSEdge.h.
Referenced by decVaporization(), incVaporization(), and isVaporizing().
The documentation for this class was generated from the following files:
MSEdge.h
MSEdge.cpp