SUMO - Simulation of Urban MObility: NBNetBuilder Class Reference
NBNetBuilder Class Reference
Instance responsible for building networks.
#include <NBNetBuilder.h>
Data Structures
class by_id_sorter
Sorts nodes by their ids.
Public Member Functions
void applyOptions (OptionsCont &oc)
Initialises the storage by applying given options.
void compute (OptionsCont &oc, const std::set< std::string > &explicitTurnarounds=std::set< std::string >(), bool removeElements=true)
Performs the network building steps.
void haveSeenRoundabouts ()
declare that roundabouts have been seen during loading
NBNetBuilder ()
Constructor.
~NBNetBuilder ()
Destructor.
Retrieval of subcontainers
NBEdgeCont & getEdgeCont ()
Returns the edge container.
NBNodeCont & getNodeCont ()
Returns the node container.
NBTypeCont & getTypeCont ()
Returns the type container.
NBTrafficLightLogicCont & getTLLogicCont ()
Returns the traffic light logics container.
NBDistrictCont & getDistrictCont ()
Returns the districts container.
const std::vector< EdgeVector > & getRoundabouts () const
Returns the determined roundabouts.
const NBJoinedEdgesMap & getJoinedEdgesMap () const
Returns the joined edges map.
Static Public Member Functions
static bool transformCoordinates (Position &from, bool includeInBoundary=true, GeoConvHelper *from_srs=0)
transforms loaded coordinates handles projections, offsets (using GeoConvHelper) and import of height data (using Heightmapper if available)
static bool transformCoordinates (PositionVector &from, bool includeInBoundary=true, GeoConvHelper *from_srs=0)
Protected Attributes
NBDistrictCont myDistrictCont
The used container for districts.
NBEdgeCont myEdgeCont
The used container for edges.
bool myHaveSeenRoundabouts
whether a sumo network with roundabout information was loaded
NBJoinedEdgesMap myJoinedEdges
Map of joined edges.
NBNodeCont myNodeCont
The used container for nodes.
std::vector< EdgeVector > myRoundabouts
Edges marked as belonging to a roundabout (each EdgeVector is a roundabout)
NBTrafficLightLogicCont myTLLCont
The used container for traffic light logics.
NBTypeCont myTypeCont
The used container for street types.
Private Member Functions
void moveToOrigin (GeoConvHelper &geoConvHelper)
shift network so its lower left corner is at 0,0
NBNetBuilder (const NBNetBuilder &s)
invalidated copy constructor
NBNetBuilder & operator= (const NBNetBuilder &s)
invalidated assignment operator
Friends
class GNENet
Detailed Description
Instance responsible for building networks.
The class' - and the netbuild module's - functionality is embedded within the compute() method.
Definition at line 113 of file NBNetBuilder.h.
Constructor & Destructor Documentation
NBNetBuilder::NBNetBuilder ()
Constructor.
Definition at line 68 of file NBNetBuilder.cpp.
NBNetBuilder::~NBNetBuilder ()
Destructor.
Definition at line 74 of file NBNetBuilder.cpp.
NBNetBuilder::NBNetBuilder (const NBNetBuilder & s) private
invalidated copy constructor
Member Function Documentation
void NBNetBuilder::applyOptions (OptionsCont & oc)
Initialises the storage by applying given options.
Options, mainly steering the acceptance of edges, are parsed and the according internal variables are set.
Parameters
[in] oc The options container to read options from
Exceptions
ProcessError If something fails (message is included)
Definition at line 78 of file NBNetBuilder.cpp.
References NBTrafficLightLogicCont::applyOptions(), NBEdgeCont::applyOptions(), OptionsCont::getFloat(), OptionsCont::getInt(), OptionsCont::getString(), OptionsCont::isSet(), myEdgeCont, myTLLCont, myTypeCont, OptionsCont::set(), and NBTypeCont::setDefaults().
Referenced by main().
void NBNetBuilder::compute (OptionsCont & oc, const std::set< std::string > & explicitTurnarounds = std::set<std::string>(), bool removeElements = true)
Performs the network building steps.
Parameters
[in] oc Container that contains options for building
[in] explicitTurnarounds List of edge ids for which turn-arounds should be added (used by NETEDIT)
[in] removeElements whether processing steps which cause nodes and edges to be removed shall be triggered
Exceptions
ProcessError (recheck)
Definition at line 108 of file NBNetBuilder.cpp.
References Boundary::add(), NBNodeCont::addJoinExclusion(), NBEdgeCont::appendTurnarounds(), NBNodeCont::begin(), NBEdgeCont::begin(), NBEdgeCont::checkGeometries(), NBEdgeCont::computeEdge2Edges(), NBEdgePriorityComputer::computeEdgePriorities(), NBEdgeCont::computeEdgeShapes(), GeoConvHelper::computeFinal(), NBEdgeCont::computeLanes2Edges(), NBNodeCont::computeLanes2Lanes(), NBEdgeCont::computeLaneShapes(), NBTrafficLightLogicCont::computeLogics(), NBNodeCont::computeLogics(), NBNodeCont::computeNodeShapes(), NBNodeTypeComputer::computeNodeTypes(), NBRampsComputer::computeRamps(), NBTurningDirectionsComputer::computeTurnDirections(), NBNodeCont::end(), NBEdgeCont::end(), OptionsCont::exists(), NBEdgeCont::generateStreetSigns(), StringBijection< T >::get(), OptionsCont::getBool(), GeoConvHelper::getConvBoundary(), OptionsCont::getFloat(), GeoConvHelper::getOffsetBase(), GeoConvHelper::getOrigBoundary(), GeoConvHelper::getProcessing(), OptionsCont::getString(), OptionsCont::getStringVector(), NBEdgeCont::guessRoundabouts(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), NBJoinedEdgesMap::init(), OptionsCont::isDefault(), OptionsCont::isSet(), NBNodeCont::joinJunctions(), NBNodeCont::joinLoadedClusters(), NBNodeCont::joinSimilarEdges(), NBNodeCont::joinTLS(), MAX2(), MIN2(), moveToOrigin(), myDistrictCont, myEdgeCont, myHaveSeenRoundabouts, myJoinedEdges, myNodeCont, myRoundabouts, myTLLCont, NBNodeCont::printBuiltNodesStatistics(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, NBEdgeCont::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NBEdgeCont::reduceGeometries(), NBNodeCont::removeIsolatedRoads(), NBNodeCont::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBRequest::reportWarnings(), NBNodeCont::retrieve(), NBNodeCont::setAsTLControlled(), GeoConvHelper::setConvBoundary(), NBTrafficLightLogicCont::setTLControllingInformation(), NBNodesEdgesSorter::sortNodesEdges(), NBEdgeCont::sortOutgoingLanesConnections(), NBEdgeCont::splitGeometry(), SUMOReal, toString(), SUMOXMLDefinitions::TrafficLightTypes, WRITE_MESSAGE, WRITE_WARNING, Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by main().
NBDistrictCont& NBNetBuilder::getDistrictCont () inline
Returns the districts container.
Returns
The districts container (reference)
Definition at line 186 of file NBNetBuilder.h.
References myDistrictCont.
Referenced by NIImporter_VISUM::buildDistrictNode(), NBRampsComputer::computeRamps(), NILoader::load(), NILoader::loadXML(), NIImporter_VISUM::parse_Connectors(), NIImporter_VISUM::parse_Districts(), NIImporter_VISUM::parse_Lanes(), NIImporter_Vissim::postLoadBuild(), and NWWriter_SUMO::writeNetwork().
NBEdgeCont& NBNetBuilder::getEdgeCont () inline
Returns the edge container.
Returns
The edge container (reference)
Definition at line 154 of file NBNetBuilder.h.
References myEdgeCont.
Referenced by NIImporter_SUMO::_loadNetwork(), NBRampsComputer::computeRamps(), NIImporter_VISUM::getNamedEdge(), NIImporter_VISUM::getNamedEdgeContinuating(), NIImporter_VISUM::getReversedContinuating(), NIImporter_OpenStreetMap::insertEdge(), NILoader::load(), NIImporter_RobocupRescue::loadNetwork(), NIImporter_ArcView::loadNetwork(), NIImporter_DlrNavteq::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_OpenDrive::loadNetwork(), NILoader::loadXML(), main(), NIImporter_VISUM::parse_Connectors(), NIImporter_VISUM::parse_Edges(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIImporter_Vissim::postLoadBuild(), NGNet::toNB(), NWWriter_Amitran::writeNetwork(), NWWriter_OpenDrive::writeNetwork(), NWWriter_MATSim::writeNetwork(), NWWriter_DlrNavteq::writeNetwork(), NWWriter_XML::writeNetwork(), and NWWriter_SUMO::writeNetwork().
const NBJoinedEdgesMap& NBNetBuilder::getJoinedEdgesMap () const inline
Returns the joined edges map.
Returns
The map of joined edges
Definition at line 202 of file NBNetBuilder.h.
References myJoinedEdges.
Referenced by NWFrame::writeNetwork().
NBNodeCont& NBNetBuilder::getNodeCont () inline
Returns the node container.
Returns
The node container (reference)
Definition at line 162 of file NBNetBuilder.h.
References myNodeCont.
Referenced by NIImporter_VISUM::buildDistrictNode(), NGEdge::buildNBEdge(), NBRampsComputer::computeRamps(), NIImporter_VISUM::getNamedNode(), NIImporter_OpenStreetMap::insertEdge(), NILoader::load(), NIImporter_OpenStreetMap::load(), NIImporter_RobocupRescue::loadNetwork(), NIImporter_ArcView::loadNetwork(), NIImporter_DlrNavteq::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_OpenDrive::loadNetwork(), NILoader::loadXML(), main(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_Nodes(), NIImporter_VISUM::parse_NodesToTrafficLights(), NIImporter_Vissim::postLoadBuild(), NGNet::toNB(), NWWriter_Amitran::writeNetwork(), NWWriter_OpenDrive::writeNetwork(), NWWriter_MATSim::writeNetwork(), NWWriter_DlrNavteq::writeNetwork(), NWWriter_XML::writeNetwork(), and NWWriter_SUMO::writeNetwork().
const std::vector<EdgeVector>& NBNetBuilder::getRoundabouts () const inline
Returns the determined roundabouts.
Returns
The list of roundabout edges
Definition at line 194 of file NBNetBuilder.h.
References myRoundabouts.
Referenced by NWWriter_Amitran::writeNetwork(), and NWWriter_SUMO::writeNetwork().
NBTrafficLightLogicCont& NBNetBuilder::getTLLogicCont () inline
Returns the traffic light logics container.
Returns
The traffic light logics container (reference)
Definition at line 178 of file NBNetBuilder.h.
References myTLLCont.
Referenced by NGNode::buildNBNode(), NIImporter_OpenStreetMap::insertEdge(), NILoader::load(), NIImporter_VISUM::load(), NIImporter_OpenStreetMap::load(), NIImporter_DlrNavteq::loadNetwork(), NIImporter_OpenDrive::loadNetwork(), NILoader::loadXML(), NIImporter_Vissim::postLoadBuild(), NWWriter_XML::writeNetwork(), and NWWriter_SUMO::writeNetwork().
NBTypeCont& NBNetBuilder::getTypeCont () inline
Returns the type container.
Returns
The type container (reference)
Definition at line 170 of file NBNetBuilder.h.
References myTypeCont.
Referenced by NGEdge::buildNBEdge(), NIImporter_OpenStreetMap::insertEdge(), NILoader::load(), NIImporter_OpenStreetMap::load(), NIImporter_ArcView::loadNetwork(), NIImporter_OpenDrive::loadNetwork(), NILoader::loadXML(), NIImporter_VISUM::parse_Edges(), NIImporter_VISUM::parse_Types(), and NGNet::toNB().
void NBNetBuilder::haveSeenRoundabouts () inline
declare that roundabouts have been seen during loading
Definition at line 209 of file NBNetBuilder.h.
References myHaveSeenRoundabouts.
Referenced by NIImporter_SUMO::myStartElement().
void NBNetBuilder::moveToOrigin (GeoConvHelper & geoConvHelper) private
shift network so its lower left corner is at 0,0
Definition at line 420 of file NBNetBuilder.cpp.
References NBDistrictCont::begin(), NBNodeCont::begin(), NBEdgeCont::begin(), NBDistrictCont::end(), NBNodeCont::end(), NBEdgeCont::end(), GeoConvHelper::getConvBoundary(), GeoConvHelper::moveConvertedBy(), myDistrictCont, myEdgeCont, myNodeCont, PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, SUMOReal, Boundary::xmin(), and Boundary::ymin().
Referenced by compute().
NBNetBuilder& NBNetBuilder::operator= (const NBNetBuilder & s) private
invalidated assignment operator
bool NBNetBuilder::transformCoordinates (Position & from, bool includeInBoundary = true, GeoConvHelper * from_srs = 0) static
transforms loaded coordinates handles projections, offsets (using GeoConvHelper) and import of height data (using Heightmapper if available)
Parameters
[in,out] from The coordinate to be transformed
[in] includeInBoundary Whether to patch the convex boundary of the GeoConvHelper default instance
[in] from_srs The spatial reference system of the input coordinate These methods are located outside of GeoConvHelper to avoid linker-dependecies on INTERNAL_LIBS and GDAL for libgeom
Definition at line 440 of file NBNetBuilder.cpp.
References GeoConvHelper::cartesian2geo(), GeoConvHelper::getProcessing(), SUMOReal, UNUSED_PARAMETER, GeoConvHelper::usingGeoProjection(), Position::x(), GeoConvHelper::x2cartesian(), and Position::y().
Referenced by NIImporter_SUMO::addEdge(), NIImporter_SUMO::addJunction(), NIImporter_SUMO::addLane(), NIXMLNodesHandler::addNode(), NIImporter_OpenDrive::computeShapes(), NBEdgeCont::ignoreFilterMatch(), NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenStreetMap::insertNodeChecking(), NIImporter_ArcView::load(), NIImporter_RobocupRescue::loadNodes(), NIImporter_ITSUMO::Handler::myEndElement(), NIImporter_MATSim::NodesHandler::myStartElement(), NIVissimAbstractEdge::NIVissimAbstractEdge(), NIImporter_VISUM::parse_Districts(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Nodes(), NIImporter_VISUM::parse_Point(), NIImporter_DlrNavteq::NodesHandler::report(), transformCoordinates(), and NIXMLEdgesHandler::tryGetShape().
bool NBNetBuilder::transformCoordinates (PositionVector & from, bool includeInBoundary = true, GeoConvHelper * from_srs = 0) static
Definition at line 462 of file NBNetBuilder.cpp.
References OptionsCont::getFloat(), OptionsCont::getOptions(), PositionVector::insertAt(), SUMOReal, and transformCoordinates().
Friends And Related Function Documentation
friend class GNENet friend
Definition at line 114 of file NBNetBuilder.h.
Field Documentation
NBDistrictCont NBNetBuilder::myDistrictCont protected
The used container for districts.
Definition at line 255 of file NBNetBuilder.h.
Referenced by compute(), getDistrictCont(), and moveToOrigin().
NBEdgeCont NBNetBuilder::myEdgeCont protected
The used container for edges.
Definition at line 249 of file NBNetBuilder.h.
Referenced by applyOptions(), compute(), getEdgeCont(), and moveToOrigin().
bool NBNetBuilder::myHaveSeenRoundabouts protected
whether a sumo network with roundabout information was loaded
Definition at line 258 of file NBNetBuilder.h.
Referenced by compute(), and haveSeenRoundabouts().
NBJoinedEdgesMap NBNetBuilder::myJoinedEdges protected
Map of joined edges.
Definition at line 264 of file NBNetBuilder.h.
Referenced by compute(), and getJoinedEdgesMap().
NBNodeCont NBNetBuilder::myNodeCont protected
The used container for nodes.
Definition at line 243 of file NBNetBuilder.h.
Referenced by compute(), getNodeCont(), and moveToOrigin().
std::vector<EdgeVector> NBNetBuilder::myRoundabouts protected
Edges marked as belonging to a roundabout (each EdgeVector is a roundabout)
Definition at line 261 of file NBNetBuilder.h.
Referenced by compute(), and getRoundabouts().
NBTrafficLightLogicCont NBNetBuilder::myTLLCont protected
The used container for traffic light logics.
Definition at line 252 of file NBNetBuilder.h.
Referenced by applyOptions(), compute(), and getTLLogicCont().
NBTypeCont NBNetBuilder::myTypeCont protected
The used container for street types.
Definition at line 246 of file NBNetBuilder.h.
Referenced by applyOptions(), and getTypeCont().
The documentation for this class was generated from the following files:
NBNetBuilder.h
NBNetBuilder.cpp