SUMO - Simulation of Urban MObility: SUMOAbstractRouter< E, V > Class Template Reference
SUMOAbstractRouter< E, V > Class Template Reference abstract
#include <SUMOAbstractRouter.h>
Public Member Functions
virtual void compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > &into)=0
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
void endQuery (int visits)
virtual void prepare (const E *, const V *, bool)
virtual SUMOReal recomputeCosts (const std::vector< const E * > &edges, const V *const v, SUMOTime msTime) const =0
void startQuery ()
SUMOAbstractRouter (const std::string &type)
Constructor.
virtual ~SUMOAbstractRouter ()
Destructor.
Private Member Functions
SUMOAbstractRouter & operator= (const SUMOAbstractRouter &s)
Invalidated assignment operator.
Private Attributes
int myNumQueries
long myQueryStartTime
the time spent querying in milliseconds
long myQueryTimeSum
int myQueryVisits
counters for performance logging
const std::string myType
the type of this router
Detailed Description
template<class E, class V>
class SUMOAbstractRouter< E, V >
The interface for routing the vehicles over the network.
Definition at line 53 of file SUMOAbstractRouter.h.
Constructor & Destructor Documentation
template<class E, class V> SUMOAbstractRouter< E, V >::SUMOAbstractRouter (const std::string & type) inline
Constructor.
Definition at line 56 of file SUMOAbstractRouter.h.
template<class E, class V> virtual SUMOAbstractRouter< E, V >::~SUMOAbstractRouter () inline virtual
Destructor.
Definition at line 65 of file SUMOAbstractRouter.h.
Member Function Documentation
template<class E, class V> virtual void SUMOAbstractRouter< E, V >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > & into) pure virtual
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Implemented in PedestrianRouter< E, L, N, INTERNALROUTER >, PedestrianRouter< E, L, N, DijkstraRouterTT_Direct< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > > >, AStarRouterTTBase< E, V, PF >, AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >, DijkstraRouterTTBase< E, V, PF >, DijkstraRouterTTBase< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > >, DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >, DijkstraRouterEffortBase< E, V, PF >, DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >, and ROJTRRouter.
Referenced by TraCIServerAPI_Simulation::commandDistanceRequest(), MSTriggeredRerouter::notifyEnter(), RORouteDef::preComputeCurrentRoute(), TraCIServerAPI_Vehicle::processSet(), RORouteDef::repairCurrentRoute(), and MSBaseVehicle::reroute().
template<class E, class V> void SUMOAbstractRouter< E, V >::endQuery (int visits) inline
Definition at line 90 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V> SUMOAbstractRouter& SUMOAbstractRouter< E, V >::operator= (const SUMOAbstractRouter< E, V > & s) private
Invalidated assignment operator.
template<class E, class V> virtual void SUMOAbstractRouter< E, V >::prepare (const E * , const V * , bool) inline virtual
Definition at line 81 of file SUMOAbstractRouter.h.
template<class E, class V> virtual SUMOReal SUMOAbstractRouter< E, V >::recomputeCosts (const std::vector< const E * > & edges, const V *const v, SUMOTime msTime) const pure virtual
Implemented in PedestrianRouter< E, L, N, INTERNALROUTER >, PedestrianRouter< E, L, N, DijkstraRouterTT_Direct< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > > >, DijkstraRouterTTBase< E, V, PF >, DijkstraRouterTTBase< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > >, DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >, AStarRouterTTBase< E, V, PF >, AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >, DijkstraRouterEffortBase< E, V, PF >, DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >, and ROJTRRouter.
Referenced by RORouteDef::addAlternative().
template<class E, class V> void SUMOAbstractRouter< E, V >::startQuery () inline
Definition at line 85 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterEffortBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and AStarRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
Field Documentation
template<class E, class V> int SUMOAbstractRouter< E, V >::myNumQueries private
Definition at line 100 of file SUMOAbstractRouter.h.
Referenced by SUMOAbstractRouter< E, PedestrianTrip< E, N > >::startQuery(), and SUMOAbstractRouter< E, PedestrianTrip< E, N > >::~SUMOAbstractRouter().
template<class E, class V> long SUMOAbstractRouter< E, V >::myQueryStartTime private
the time spent querying in milliseconds
Definition at line 102 of file SUMOAbstractRouter.h.
Referenced by SUMOAbstractRouter< E, PedestrianTrip< E, N > >::endQuery(), and SUMOAbstractRouter< E, PedestrianTrip< E, N > >::startQuery().
template<class E, class V> long SUMOAbstractRouter< E, V >::myQueryTimeSum private
Definition at line 103 of file SUMOAbstractRouter.h.
Referenced by SUMOAbstractRouter< E, PedestrianTrip< E, N > >::endQuery(), and SUMOAbstractRouter< E, PedestrianTrip< E, N > >::~SUMOAbstractRouter().
template<class E, class V> int SUMOAbstractRouter< E, V >::myQueryVisits private
counters for performance logging
Definition at line 99 of file SUMOAbstractRouter.h.
Referenced by SUMOAbstractRouter< E, PedestrianTrip< E, N > >::endQuery(), and SUMOAbstractRouter< E, PedestrianTrip< E, N > >::~SUMOAbstractRouter().
template<class E, class V> const std::string SUMOAbstractRouter< E, V >::myType private
the type of this router
Definition at line 97 of file SUMOAbstractRouter.h.
Referenced by SUMOAbstractRouter< E, PedestrianTrip< E, N > >::~SUMOAbstractRouter().
The documentation for this class was generated from the following file:
SUMOAbstractRouter.h