SUMO - Simulation of Urban MObility: PedestrianRouterDijkstra< E, L, N > Class Template Reference
PedestrianRouterDijkstra< E, L, N > Class Template Reference
#include <PedestrianRouter.h>
Public Types
typedef PedestrianEdge< E, L, N > _PedestrianEdge
typedef PedestrianTrip< E, N > _PedestrianTrip
Public Member Functions
void compute (const E *from, const E *to, SUMOReal departPos, SUMOReal arrivalPos, SUMOReal speed, SUMOTime msTime, const N *onlyNode, std::vector< const E * > &into, bool allEdges=false)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
void compute (const E *, const E *, const _PedestrianTrip *const, SUMOTime, std::vector< const E * > &)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
void endQuery (int visits)
virtual void prepare (const E *, const PedestrianTrip< E, N > *, bool)
void prohibit (const std::vector< E * > &toProhibit)
SUMOReal recomputeCosts (const std::vector< const E * > &, const _PedestrianTrip *const, SUMOTime) const
void startQuery ()
Detailed Description
template<class E, class L, class N>
class PedestrianRouterDijkstra< E, L, N >
Definition at line 445 of file PedestrianRouter.h.
Member Typedef Documentation
typedef PedestrianEdge<E, L, N> PedestrianRouter< E, L, N, DijkstraRouterTT_Direct< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > > >::_PedestrianEdge inherited
Definition at line 370 of file PedestrianRouter.h.
typedef PedestrianTrip<E, N> PedestrianRouter< E, L, N, DijkstraRouterTT_Direct< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > > >::_PedestrianTrip inherited
Definition at line 371 of file PedestrianRouter.h.
Member Function Documentation
void PedestrianRouter< E, L, N, DijkstraRouterTT_Direct< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > > >::compute (const E * from, const E * to, SUMOReal departPos, SUMOReal arrivalPos, SUMOReal speed, SUMOTime msTime, const N * onlyNode, std::vector< const E * > & into, bool allEdges = false) inline inherited
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Definition at line 387 of file PedestrianRouter.h.
References PedestrianEdge< E, L, N >::getArrivalEdge(), PedestrianEdge< E, L, N >::getDepartEdge(), PedestrianRouter< E, L, N, INTERNALROUTER >::myInternalRouter, TIME2STEPS, and toString().
void PedestrianRouter< E, L, N, DijkstraRouterTT_Direct< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > > >::compute (const E * , const E * , const _PedestrianTrip * const, SUMOTime , std::vector< const E * > &) inline virtual inherited
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Implements SUMOAbstractRouter< E, PedestrianTrip< E, N > >.
Definition at line 413 of file PedestrianRouter.h.
void SUMOAbstractRouter< E, PedestrianTrip< E, N > >::endQuery (int visits) inline inherited
Definition at line 90 of file SUMOAbstractRouter.h.
References SysUtils::getCurrentMillis(), SUMOAbstractRouter< E, V >::myQueryStartTime, SUMOAbstractRouter< E, V >::myQueryTimeSum, and SUMOAbstractRouter< E, V >::myQueryVisits.
virtual void SUMOAbstractRouter< E, PedestrianTrip< E, N > >::prepare (const E * , const PedestrianTrip< E, N > * , bool) inline virtual inherited
Definition at line 81 of file SUMOAbstractRouter.h.
void PedestrianRouter< E, L, N, DijkstraRouterTT_Direct< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > > >::prohibit (const std::vector< E * > & toProhibit) inline inherited
Definition at line 422 of file PedestrianRouter.h.
References PedestrianEdge< E, L, N >::getBothDirections(), and PedestrianRouter< E, L, N, INTERNALROUTER >::myInternalRouter.
SUMOReal PedestrianRouter< E, L, N, DijkstraRouterTT_Direct< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > > >::recomputeCosts (const std::vector< const E * > & , const _PedestrianTrip * const, SUMOTime) const inline virtual inherited
Implements SUMOAbstractRouter< E, PedestrianTrip< E, N > >.
Definition at line 418 of file PedestrianRouter.h.
void SUMOAbstractRouter< E, PedestrianTrip< E, N > >::startQuery () inline inherited
Definition at line 85 of file SUMOAbstractRouter.h.
References SysUtils::getCurrentMillis(), SUMOAbstractRouter< E, V >::myNumQueries, and SUMOAbstractRouter< E, V >::myQueryStartTime.
The documentation for this class was generated from the following file:
PedestrianRouter.h